import enum
from collections.abc import Callable, Mapping, Sequence
from typing import Annotated, overload

import numpy
from numpy.typing import NDArray

import tesseract_robotics.tesseract_common._tesseract_common
import tesseract_robotics.tesseract_kinematics._tesseract_kinematics
import tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph
import tesseract_robotics.tesseract_srdf._tesseract_srdf
import tesseract_robotics.tesseract_state_solver._tesseract_state_solver

class Events(enum.Enum):
    COMMAND_APPLIED = 0

    SCENE_STATE_CHANGED = 1

Events_COMMAND_APPLIED: Events = Events.COMMAND_APPLIED

Events_SCENE_STATE_CHANGED: Events = Events.SCENE_STATE_CHANGED

class Event:
    @property
    def type(self) -> Events: ...

class CommandAppliedEvent(Event):
    @property
    def revision(self) -> int: ...

class SceneStateChangedEvent(Event):
    @property
    def state(
        self,
    ) -> tesseract_robotics.tesseract_state_solver._tesseract_state_solver.SceneState: ...

def cast_CommandAppliedEvent(arg: Event, /) -> CommandAppliedEvent:
    """Cast Event to CommandAppliedEvent"""

def cast_SceneStateChangedEvent(arg: Event, /) -> SceneStateChangedEvent:
    """Cast Event to SceneStateChangedEvent"""

class EventCallbackFn:
    def __init__(self, callback: Callable) -> None: ...

class Command:
    def getType(self) -> "tesseract_environment::CommandType": ...

class RemoveJointCommand(Command):
    def __init__(self, joint_name: str) -> None: ...
    def getJointName(self) -> str: ...

class AddLinkCommand(Command):
    @overload
    def __init__(
        self,
        link: tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.Link,
        replace_allowed: bool = False,
    ) -> None: ...
    @overload
    def __init__(
        self,
        link: tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.Link,
        joint: tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.Joint,
        replace_allowed: bool = False,
    ) -> None: ...
    def getLink(self) -> tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.Link: ...
    def getJoint(self) -> tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.Joint: ...
    def replaceAllowed(self) -> bool: ...

class RemoveLinkCommand(Command):
    def __init__(self, link_name: str) -> None: ...
    def getLinkName(self) -> str: ...

class AddSceneGraphCommand(Command):
    @overload
    def __init__(
        self,
        scene_graph: tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.SceneGraph,
        prefix: str = "",
    ) -> None: ...
    @overload
    def __init__(
        self,
        scene_graph: tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.SceneGraph,
        joint: tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.Joint,
        prefix: str = "",
    ) -> None: ...
    def getSceneGraph(
        self,
    ) -> tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.SceneGraph: ...
    def getJoint(self) -> tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.Joint: ...
    def getPrefix(self) -> str: ...

class ModifyAllowedCollisionsType(enum.Enum):
    ADD = 0

    REMOVE = 1

    REPLACE = 2

ModifyAllowedCollisionsType_ADD: ModifyAllowedCollisionsType = ModifyAllowedCollisionsType.ADD

ModifyAllowedCollisionsType_REMOVE: ModifyAllowedCollisionsType = ModifyAllowedCollisionsType.REMOVE

ModifyAllowedCollisionsType_REPLACE: ModifyAllowedCollisionsType = (
    ModifyAllowedCollisionsType.REPLACE
)

class ModifyAllowedCollisionsCommand(Command):
    def __init__(
        self,
        acm: tesseract_robotics.tesseract_common._tesseract_common.AllowedCollisionMatrix,
        type: ModifyAllowedCollisionsType,
    ) -> None: ...
    def getModifyType(self) -> ModifyAllowedCollisionsType: ...
    def getAllowedCollisionMatrix(
        self,
    ) -> tesseract_robotics.tesseract_common._tesseract_common.AllowedCollisionMatrix: ...

class RemoveAllowedCollisionLinkCommand(Command):
    def __init__(self, link_name: str) -> None: ...
    def getLinkName(self) -> str: ...

class ChangeJointPositionLimitsCommand(Command):
    @overload
    def __init__(self, joint_name: str, lower: float, upper: float) -> None: ...
    @overload
    def __init__(self, limits: Mapping[str, tuple[float, float]]) -> None: ...
    def getLimits(self) -> dict[str, tuple[float, float]]: ...

class ChangeJointVelocityLimitsCommand(Command):
    @overload
    def __init__(self, joint_name: str, limit: float) -> None: ...
    @overload
    def __init__(self, limits: Mapping[str, float]) -> None: ...
    def getLimits(self) -> dict[str, float]: ...

class ChangeJointAccelerationLimitsCommand(Command):
    @overload
    def __init__(self, joint_name: str, limit: float) -> None: ...
    @overload
    def __init__(self, limits: Mapping[str, float]) -> None: ...
    def getLimits(self) -> dict[str, float]: ...

class ChangeCollisionMarginsCommand(Command):
    @overload
    def __init__(
        self,
        default_margin: float,
        override_type: tesseract_robotics.tesseract_common._tesseract_common.CollisionMarginOverrideType = tesseract_robotics.tesseract_common._tesseract_common.CollisionMarginOverrideType.OVERRIDE_DEFAULT_MARGIN,
    ) -> None: ...
    @overload
    def __init__(
        self,
        collision_margin_data: tesseract_robotics.tesseract_common._tesseract_common.CollisionMarginData,
        override_type: tesseract_robotics.tesseract_common._tesseract_common.CollisionMarginOverrideType = tesseract_robotics.tesseract_common._tesseract_common.CollisionMarginOverrideType.REPLACE,
    ) -> None: ...
    def getCollisionMarginData(
        self,
    ) -> tesseract_robotics.tesseract_common._tesseract_common.CollisionMarginData: ...
    def getCollisionMarginOverrideType(
        self,
    ) -> tesseract_robotics.tesseract_common._tesseract_common.CollisionMarginOverrideType: ...

class ChangeLinkCollisionEnabledCommand(Command):
    def __init__(self, link_name: str, enabled: bool) -> None: ...
    def getLinkName(self) -> str: ...
    def getEnabled(self) -> bool: ...

class ChangeLinkVisibilityCommand(Command):
    def __init__(self, link_name: str, visible: bool) -> None: ...
    def getLinkName(self) -> str: ...
    def getEnabled(self) -> bool: ...

class ChangeJointOriginCommand(Command):
    def __init__(
        self,
        joint_name: str,
        origin: tesseract_robotics.tesseract_common._tesseract_common.Isometry3d,
    ) -> None: ...
    def getJointName(self) -> str: ...
    def getOrigin(self) -> tesseract_robotics.tesseract_common._tesseract_common.Isometry3d: ...

class ChangeLinkOriginCommand(Command):
    def __init__(
        self,
        link_name: str,
        origin: tesseract_robotics.tesseract_common._tesseract_common.Isometry3d,
    ) -> None: ...
    def getLinkName(self) -> str: ...
    def getOrigin(self) -> tesseract_robotics.tesseract_common._tesseract_common.Isometry3d: ...

class MoveJointCommand(Command):
    def __init__(self, joint_name: str, parent_link: str) -> None: ...
    def getJointName(self) -> str: ...
    def getParentLink(self) -> str: ...

class MoveLinkCommand(Command):
    def __init__(
        self, joint: tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.Joint
    ) -> None: ...
    def getJoint(self) -> tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.Joint: ...

class ReplaceJointCommand(Command):
    def __init__(
        self, joint: tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.Joint
    ) -> None: ...
    def getJoint(self) -> tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.Joint: ...

class Environment:
    def __init__(self) -> None: ...
    @overload
    def init(
        self,
        scene_graph: tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.SceneGraph,
    ) -> bool: ...
    @overload
    def init(
        self,
        scene_graph: tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.SceneGraph,
        srdf: tesseract_robotics.tesseract_srdf._tesseract_srdf.SRDFModel,
    ) -> bool: ...
    @overload
    def init(
        self,
        urdf_path: str,
        srdf_path: str,
        locator: tesseract_robotics.tesseract_common._tesseract_common.ResourceLocator,
    ) -> bool: ...
    @overload
    def init(
        self,
        urdf_or_path: str,
        locator: tesseract_robotics.tesseract_common._tesseract_common.ResourceLocator,
    ) -> bool: ...
    def initFromUrdf(
        self,
        urdf_string: str,
        locator: tesseract_robotics.tesseract_common._tesseract_common.ResourceLocator,
    ) -> bool: ...
    def initFromUrdfSrdf(
        self,
        urdf_string: str,
        srdf_string: str,
        locator: tesseract_robotics.tesseract_common._tesseract_common.ResourceLocator,
    ) -> bool: ...
    def isInitialized(self) -> bool: ...
    def reset(self) -> bool: ...
    def clear(self) -> None: ...
    def getRevision(self) -> int: ...
    def getName(self) -> str: ...
    def setName(self, name: str) -> None: ...
    def getSceneGraph(
        self,
    ) -> tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.SceneGraph: ...
    def getState(
        self,
    ) -> tesseract_robotics.tesseract_state_solver._tesseract_state_solver.SceneState: ...
    def getStateByMap(
        self, joints: Mapping[str, float]
    ) -> tesseract_robotics.tesseract_state_solver._tesseract_state_solver.SceneState: ...
    def getStateByNamesAndValues(
        self,
        joint_names: Sequence[str],
        joint_values: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)],
    ) -> tesseract_robotics.tesseract_state_solver._tesseract_state_solver.SceneState: ...
    @overload
    def setState(self, joints: Mapping[str, float]) -> None: ...
    @overload
    def setState(
        self,
        joint_names: Sequence[str],
        joint_values: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)],
    ) -> None: ...
    def setStateByNamesAndValues(
        self,
        joint_names: Sequence[str],
        joint_values: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)],
    ) -> None: ...
    def addEventCallback(self, hash: int, fn: EventCallbackFn) -> None: ...
    def removeEventCallback(self, hash: int) -> None: ...
    def clearEventCallbacks(self) -> None: ...
    @overload
    def applyCommand(self, command: RemoveJointCommand) -> bool: ...
    @overload
    def applyCommand(self, command: AddLinkCommand) -> bool: ...
    @overload
    def applyCommand(self, command: RemoveLinkCommand) -> bool: ...
    @overload
    def applyCommand(self, command: AddSceneGraphCommand) -> bool: ...
    @overload
    def applyCommand(self, command: ModifyAllowedCollisionsCommand) -> bool: ...
    @overload
    def applyCommand(self, command: RemoveAllowedCollisionLinkCommand) -> bool: ...
    @overload
    def applyCommand(self, command: ChangeJointPositionLimitsCommand) -> bool: ...
    @overload
    def applyCommand(self, command: ChangeJointVelocityLimitsCommand) -> bool: ...
    @overload
    def applyCommand(self, command: ChangeJointAccelerationLimitsCommand) -> bool: ...
    @overload
    def applyCommand(self, command: ChangeCollisionMarginsCommand) -> bool: ...
    @overload
    def applyCommand(self, command: ChangeLinkCollisionEnabledCommand) -> bool: ...
    @overload
    def applyCommand(self, command: ChangeLinkVisibilityCommand) -> bool: ...
    @overload
    def applyCommand(self, command: ChangeJointOriginCommand) -> bool: ...
    @overload
    def applyCommand(self, command: ChangeLinkOriginCommand) -> bool: ...
    @overload
    def applyCommand(self, command: MoveJointCommand) -> bool: ...
    @overload
    def applyCommand(self, command: MoveLinkCommand) -> bool: ...
    @overload
    def applyCommand(self, command: ReplaceJointCommand) -> bool: ...
    def getStateSolver(
        self,
    ) -> tesseract_robotics.tesseract_state_solver._tesseract_state_solver.StateSolver: ...
    def getJointNames(self) -> list[str]: ...
    def getActiveJointNames(self) -> list[str]: ...
    def getLinkNames(self) -> list[str]: ...
    def getActiveLinkNames(self) -> list[str]: ...
    def getStaticLinkNames(self) -> list[str]: ...
    def getRootLinkName(self) -> str: ...
    def getCurrentJointValues(
        self,
    ) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order="C")]: ...
    def getCurrentJointValuesByNames(
        self, joint_names: Sequence[str]
    ) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order="C")]: ...
    def getLinkTransform(
        self, link_name: str
    ) -> tesseract_robotics.tesseract_common._tesseract_common.Isometry3d: ...
    def getRelativeLinkTransform(
        self, from_link_name: str, to_link_name: str
    ) -> tesseract_robotics.tesseract_common._tesseract_common.Isometry3d: ...
    def getLink(
        self, name: str
    ) -> tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.Link: ...
    def getJoint(
        self, name: str
    ) -> tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.Joint: ...
    def getGroupNames(self) -> set[str]: ...
    def getGroupJointNames(self, group_name: str) -> list[str]: ...
    def getJointGroup(
        self, group_name: str
    ) -> tesseract_robotics.tesseract_kinematics._tesseract_kinematics.JointGroup: ...
    def getKinematicGroup(
        self, group_name: str, ik_solver_name: str = ""
    ) -> tesseract_robotics.tesseract_kinematics._tesseract_kinematics.KinematicGroup: ...
    def findTCPOffset(
        self, manip_info: tesseract_robotics.tesseract_common._tesseract_common.ManipulatorInfo
    ) -> tesseract_robotics.tesseract_common._tesseract_common.Isometry3d: ...
    def getDiscreteContactManager(self) -> "tesseract_collision::DiscreteContactManager": ...
    def getContinuousContactManager(self) -> "tesseract_collision::ContinuousContactManager": ...
    def setActiveDiscreteContactManager(self, name: str) -> bool: ...
    def setActiveContinuousContactManager(self, name: str) -> bool: ...
    def getAllowedCollisionMatrix(
        self,
    ) -> tesseract_robotics.tesseract_common._tesseract_common.AllowedCollisionMatrix: ...
    def getCollisionMarginData(
        self,
    ) -> tesseract_robotics.tesseract_common._tesseract_common.CollisionMarginData: ...
    def setResourceLocator(
        self, locator: tesseract_robotics.tesseract_common._tesseract_common.ResourceLocator
    ) -> None: ...
    def getResourceLocator(
        self,
    ) -> tesseract_robotics.tesseract_common._tesseract_common.ResourceLocator: ...
    def getKinematicsInformation(
        self,
    ) -> tesseract_robotics.tesseract_srdf._tesseract_srdf.KinematicsInformation: ...
