"""tesseract_motion_planners Python bindings"""



class PlannerRequest:
    def __init__(self) -> None: ...

    @property
    def name(self) -> str: ...

    @name.setter
    def name(self, arg: str, /) -> None: ...

    @property
    def env(self) -> "tesseract::environment::Environment": ...

    @env.setter
    def env(self, arg: "tesseract::environment::Environment", /) -> None: ...

    @property
    def profiles(self) -> "tesseract::common::ProfileDictionary": ...

    @profiles.setter
    def profiles(self, arg: "tesseract::common::ProfileDictionary", /) -> None: ...

    @property
    def instructions(self) -> "tesseract::command_language::CompositeInstruction": ...

    @instructions.setter
    def instructions(self, arg: "tesseract::command_language::CompositeInstruction", /) -> None: ...

    @property
    def verbose(self) -> bool: ...

    @verbose.setter
    def verbose(self, arg: bool, /) -> None: ...

    @property
    def format_result_as_input(self) -> bool: ...

    @format_result_as_input.setter
    def format_result_as_input(self, arg: bool, /) -> None: ...

class PlannerResponse:
    def __init__(self) -> None: ...

    @property
    def results(self) -> "tesseract::command_language::CompositeInstruction": ...

    @results.setter
    def results(self, arg: "tesseract::command_language::CompositeInstruction", /) -> None: ...

    @property
    def successful(self) -> bool: ...

    @successful.setter
    def successful(self, arg: bool, /) -> None: ...

    @property
    def message(self) -> str: ...

    @message.setter
    def message(self, arg: str, /) -> None: ...

    def __bool__(self) -> bool: ...

class MotionPlanner:
    def getName(self) -> str: ...

    def solve(self, request: PlannerRequest) -> PlannerResponse: ...

    def terminate(self) -> bool: ...

    def clear(self) -> None: ...

    @staticmethod
    def checkRequest(request: PlannerRequest) -> bool: ...

    def clone(self) -> MotionPlanner: ...

def assignCurrentStateAsSeed(composite_instructions: "tesseract::command_language::CompositeInstruction", env: "tesseract::environment::Environment") -> None:
    """
    Assign the current environment state as seed to all CartesianWaypoints in the program
    """
