from collections.abc import Mapping, Sequence, Set

class KinematicsInformation:
    def __init__(self) -> None: ...
    @property
    def group_names(self) -> set[str]: ...
    @group_names.setter
    def group_names(self, arg: Set[str], /) -> None: ...
    @property
    def chain_groups(self) -> dict[str, list[tuple[str, str]]]: ...
    @chain_groups.setter
    def chain_groups(self, arg: Mapping[str, Sequence[tuple[str, str]]], /) -> None: ...
    @property
    def joint_groups(self) -> dict[str, list[str]]: ...
    @joint_groups.setter
    def joint_groups(self, arg: Mapping[str, Sequence[str]], /) -> None: ...
    @property
    def link_groups(self) -> dict[str, list[str]]: ...
    @link_groups.setter
    def link_groups(self, arg: Mapping[str, Sequence[str]], /) -> None: ...
    @property
    def group_states(self) -> dict[str, dict[str, dict[str, float]]]: ...
    @group_states.setter
    def group_states(self, arg: Mapping[str, Mapping[str, Mapping[str, float]]], /) -> None: ...
    @property
    def group_tcps(self) -> dict[str, dict[str, "Eigen::Transform<double, 3, 1, 0>"]]: ...
    @group_tcps.setter
    def group_tcps(
        self, arg: Mapping[str, Mapping[str, "Eigen::Transform<double, 3, 1, 0>"]], /
    ) -> None: ...
    def insert(self, other: KinematicsInformation) -> None: ...
    def clear(self) -> None: ...
    def hasGroup(self, group_name: str) -> bool: ...
    def addChainGroup(self, group_name: str, chain_group: Sequence[tuple[str, str]]) -> None: ...
    def removeChainGroup(self, group_name: str) -> None: ...
    def hasChainGroup(self, group_name: str) -> bool: ...
    def addJointGroup(self, group_name: str, joint_group: Sequence[str]) -> None: ...
    def removeJointGroup(self, group_name: str) -> None: ...
    def hasJointGroup(self, group_name: str) -> bool: ...
    def addLinkGroup(self, group_name: str, link_group: Sequence[str]) -> None: ...
    def removeLinkGroup(self, group_name: str) -> None: ...
    def hasLinkGroup(self, group_name: str) -> bool: ...
    def addGroupJointState(
        self, group_name: str, state_name: str, joint_state: Mapping[str, float]
    ) -> None: ...
    def removeGroupJointState(self, group_name: str, state_name: str) -> None: ...
    def hasGroupJointState(self, group_name: str, state_name: str) -> bool: ...
    def addGroupTCP(
        self, group_name: str, tcp_name: str, tcp: "Eigen::Transform<double, 3, 1, 0>"
    ) -> None: ...
    def removeGroupTCP(self, group_name: str, tcp_name: str) -> None: ...
    def hasGroupTCP(self, group_name: str, tcp_name: str) -> bool: ...
    def __eq__(self, arg: KinematicsInformation, /) -> bool: ...
    def __ne__(self, arg: KinematicsInformation, /) -> bool: ...

class SRDFModel:
    def __init__(self) -> None: ...
    def initFile(
        self,
        scene_graph: "tesseract_scene_graph::SceneGraph",
        filename: str,
        locator: "tesseract_common::ResourceLocator",
    ) -> None: ...
    def initString(
        self,
        scene_graph: "tesseract_scene_graph::SceneGraph",
        xmlstring: str,
        locator: "tesseract_common::ResourceLocator",
    ) -> None: ...
    def saveToFile(self, file_path: str) -> bool: ...
    def clear(self) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, arg: str, /) -> None: ...
    @property
    def version(self) -> list[int]: ...
    @version.setter
    def version(self, arg: Sequence[int], /) -> None: ...
    @property
    def kinematics_information(self) -> KinematicsInformation: ...
    @kinematics_information.setter
    def kinematics_information(self, arg: KinematicsInformation, /) -> None: ...
    @property
    def acm(self) -> "tesseract_common::AllowedCollisionMatrix": ...
    @acm.setter
    def acm(self, arg: "tesseract_common::AllowedCollisionMatrix", /) -> None: ...
    @property
    def collision_margin_data(self) -> "tesseract_common::CollisionMarginData": ...
    @collision_margin_data.setter
    def collision_margin_data(self, arg: "tesseract_common::CollisionMarginData", /) -> None: ...
    @property
    def calibration_info(self) -> "tesseract_common::CalibrationInfo": ...
    @calibration_info.setter
    def calibration_info(self, arg: "tesseract_common::CalibrationInfo", /) -> None: ...
    def __eq__(self, arg: SRDFModel, /) -> bool: ...
    def __ne__(self, arg: SRDFModel, /) -> bool: ...
    def __repr__(self) -> str: ...

def processSRDFAllowedCollisions(
    scene_graph: "tesseract_scene_graph::SceneGraph", srdf_model: SRDFModel
) -> None:
    """Process SRDF allowed collisions and add to scene graph ACM"""
