"""Content-addressed emit identity — reproducibility made structural.

Package version + SHA-256 of (a) the canonical IR and (b) the profiles repr,
embedded as comment header lines in every emitted file. No timestamps in the
body, so same inputs → byte-identical output and goldens diff meaningfully.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass
from importlib.metadata import PackageNotFoundError, version

from .events import ProgramIR

_DIGEST_PREFIX = "sha256:"


def _sha256(text: str) -> str:
    return _DIGEST_PREFIX + hashlib.sha256(text.encode("utf-8")).hexdigest()


def _package_version() -> str:
    try:
        return version("tesseract_robotics")
    except PackageNotFoundError:
        return "0+unknown"


@dataclass(frozen=True)
class EmitIdentity:
    """Version + digests identifying one emit. Build via ``EmitIdentity.build``."""

    package_version: str
    ir_digest: str
    profiles_digest: str

    @classmethod
    def build(cls, ir: ProgramIR, *, profiles_repr: str) -> EmitIdentity:
        """Compute identity from a lowered program and a deterministic profiles repr."""
        return cls(
            package_version=_package_version(),
            ir_digest=_sha256(ir.canonical()),
            profiles_digest=_sha256(profiles_repr),
        )

    def header_lines(self) -> list[str]:
        """Comment-prefix-agnostic identity lines (caller adds the comment token)."""
        return [
            f"generated by tesseract_robotics.emitters {self.package_version}",
            f"ir-digest: {self.ir_digest}",
            f"profiles-digest: {self.profiles_digest}",
            "DO NOT EDIT - regenerate from the planning pipeline",
        ]
