from collections.abc import Sequence
import datetime
from typing import overload


class TaskComposerKeys:
    def __init__(self) -> None: ...

    def add(self, port: str, key: str) -> None: ...

    def addKeys(self, port: str, keys: Sequence[str]) -> None: ...

    def get(self, port: str) -> str: ...

    def has(self, port: str) -> bool: ...

    def empty(self) -> bool: ...

    def size(self) -> int: ...

    def data(self) -> dict[str, str | list[str]]: ...

class TaskComposerDataStorage:
    def __init__(self) -> None: ...

    def getName(self) -> str: ...

    def setName(self, name: str) -> None: ...

    def hasKey(self, key: str) -> bool: ...

    def setData(self, key: str, data: AnyPoly) -> None: ...

    def getData(self, key: str) -> AnyPoly: ...

    def removeData(self, key: str) -> None: ...

def createTaskComposerDataStorage() -> TaskComposerDataStorage:
    """Create a TaskComposerDataStorage as shared_ptr"""

class TaskComposerNodeInfo:
    @property
    def name(self) -> str: ...

    @property
    def return_value(self) -> int: ...

    @property
    def status_code(self) -> int: ...

    @property
    def status_message(self) -> str: ...

    @property
    def elapsed_time(self) -> float: ...

class TaskComposerNodeInfoContainer:
    def __init__(self) -> None: ...

    def getAbortingNodeInfo(self) -> object: ...

    def getAllInfos(self) -> list: ...

class TaskComposerContext:
    @property
    def name(self) -> str: ...

    @name.setter
    def name(self, arg: str, /) -> None: ...

    @property
    def dotgraph(self) -> bool: ...

    @dotgraph.setter
    def dotgraph(self, arg: bool, /) -> None: ...

    @property
    def data_storage(self) -> TaskComposerDataStorage: ...

    @data_storage.setter
    def data_storage(self, arg: TaskComposerDataStorage, /) -> None: ...

    def isAborted(self) -> bool: ...

    def isSuccessful(self) -> bool: ...

    @property
    def task_infos(self) -> TaskComposerNodeInfoContainer: ...

class TaskComposerNode:
    def getName(self) -> str: ...

    def getNamespace(self) -> str: ...

    def getUUIDString(self) -> str: ...

    def isConditional(self) -> bool: ...

    def getInputKeys(self) -> TaskComposerKeys: ...

    def getOutputKeys(self) -> TaskComposerKeys: ...

    def setInputKeys(self, input_keys: TaskComposerKeys) -> None: ...

    def setOutputKeys(self, output_keys: TaskComposerKeys) -> None: ...

class TaskComposerFuture:
    @property
    def context(self) -> TaskComposerContext: ...

    @context.setter
    def context(self, arg: TaskComposerContext, /) -> None: ...

    def valid(self) -> bool: ...

    def ready(self) -> bool: ...

    def wait(self) -> None: ...

    def waitFor(self, duration: datetime.timedelta | float) -> "std::__1::future_status": ...

class TaskComposerExecutor:
    def getName(self) -> str: ...

    def run(self, node: TaskComposerNode, data_storage: TaskComposerDataStorage, dotgraph: bool = False) -> TaskComposerFuture: ...

    def getWorkerCount(self) -> int: ...

    def getTaskCount(self) -> int: ...

class TaskflowTaskComposerExecutor:
    @overload
    def __init__(self, name: str = 'TaskflowExecutor', num_threads: int = 10) -> None: ...

    @overload
    def __init__(self, num_threads: int) -> None: ...

    def getName(self) -> str: ...

    def run(self, node: TaskComposerNode, data_storage: TaskComposerDataStorage, dotgraph: bool = False) -> TaskComposerFuture: ...

    def getWorkerCount(self) -> int: ...

    def getTaskCount(self) -> int: ...

class TaskComposerPluginFactory:
    def __init__(self, config: str, locator: object) -> None:
        """Create from config file path (string) and GeneralResourceLocator"""

    def createTaskComposerExecutor(self, name: str) -> TaskComposerExecutor:
        """Create a task composer executor by name"""

    def createTaskComposerNode(self, name: str) -> TaskComposerNode:
        """Create a task composer node by name"""

    def hasTaskComposerExecutorPlugins(self) -> bool: ...

    def hasTaskComposerNodePlugins(self) -> bool: ...

    def getDefaultTaskComposerExecutorPlugin(self) -> str: ...

    def getDefaultTaskComposerNodePlugin(self) -> str: ...

def createTaskComposerPluginFactory(config: str, locator: object) -> TaskComposerPluginFactory:
    """
    Create a TaskComposerPluginFactory from a config file path (string) and GeneralResourceLocator
    """

class AnyPoly:
    def __init__(self) -> None: ...

    def isNull(self) -> bool: ...

    def getTypeName(self) -> str: ...

def AnyPoly_wrap_CompositeInstruction(instruction: "tesseract_planning::CompositeInstruction") -> AnyPoly:
    """Wrap a CompositeInstruction into an AnyPoly"""

def AnyPoly_wrap_ProfileDictionary(profiles: "tesseract_planning::ProfileDictionary") -> AnyPoly:
    """Wrap a ProfileDictionary shared_ptr into an AnyPoly"""

def AnyPoly_wrap_EnvironmentConst(environment: "tesseract_environment::Environment") -> AnyPoly:
    """Wrap a const Environment shared_ptr into an AnyPoly"""

def AnyPoly_as_CompositeInstruction(any_poly: AnyPoly) -> "tesseract_planning::CompositeInstruction":
    """Extract a CompositeInstruction from an AnyPoly"""
