"""tesseract_collision Python bindings"""

from collections.abc import Mapping, Sequence
import enum
from typing import Annotated, overload

import numpy
from numpy.typing import NDArray

import tesseract_robotics.tesseract_common._tesseract_common


class ContinuousCollisionType(enum.Enum):
    CCType_None = 0

    CCType_Time0 = 1

    CCType_Time1 = 2

    CCType_Between = 3

class ContactTestType(enum.Enum):
    FIRST = 0

    CLOSEST = 1

    ALL = 2

    LIMITED = 3

ContactTestType_FIRST: ContactTestType = ContactTestType.FIRST

ContactTestType_CLOSEST: ContactTestType = ContactTestType.CLOSEST

ContactTestType_ALL: ContactTestType = ContactTestType.ALL

ContactTestType_LIMITED: ContactTestType = ContactTestType.LIMITED

class CollisionEvaluatorType(enum.Enum):
    NONE = 0

    DISCRETE = 1

    LVS_DISCRETE = 2

    CONTINUOUS = 3

    LVS_CONTINUOUS = 4

class CollisionCheckProgramType(enum.Enum):
    ALL = 0

    ALL_EXCEPT_START = 1

    ALL_EXCEPT_END = 2

    START_ONLY = 3

    END_ONLY = 4

    INTERMEDIATE_ONLY = 5

class ACMOverrideType(enum.Enum):
    NONE = 0

    ASSIGN = 1

    AND = 2

    OR = 3

class CollisionCheckExitType(enum.Enum):
    FIRST = 0

    ONE_PER_STEP = 1

    ALL = 2

class ContactResult:
    def __init__(self) -> None: ...

    @property
    def distance(self) -> float: ...

    @distance.setter
    def distance(self, arg: float, /) -> None: ...

    @property
    def type_id(self) -> list[int]: ...

    @type_id.setter
    def type_id(self, arg: Sequence[int], /) -> None: ...

    @property
    def link_names(self) -> list[str]: ...

    @link_names.setter
    def link_names(self, arg: Sequence[str], /) -> None: ...

    @property
    def shape_id(self) -> list[int]: ...

    @shape_id.setter
    def shape_id(self, arg: Sequence[int], /) -> None: ...

    @property
    def nearest_points(self) -> list[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]]: ...

    @nearest_points.setter
    def nearest_points(self, arg: Sequence[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], /) -> None: ...

    @property
    def transform(self) -> list[tesseract_robotics.tesseract_common._tesseract_common.Isometry3d]: ...

    @transform.setter
    def transform(self, arg: Sequence[tesseract_robotics.tesseract_common._tesseract_common.Isometry3d], /) -> None: ...

    @property
    def normal(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @normal.setter
    def normal(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], /) -> None: ...

    @property
    def cc_time(self) -> list[float]: ...

    @cc_time.setter
    def cc_time(self, arg: Sequence[float], /) -> None: ...

    @property
    def cc_type(self) -> list[ContinuousCollisionType]: ...

    @cc_type.setter
    def cc_type(self, arg: Sequence[ContinuousCollisionType], /) -> None: ...

    @property
    def single_contact_point(self) -> bool: ...

    @single_contact_point.setter
    def single_contact_point(self, arg: bool, /) -> None: ...

    def clear(self) -> None: ...

class ContactResultVector:
    def __init__(self) -> None: ...

    def __len__(self) -> int: ...

    def __getitem__(self, arg: int, /) -> ContactResult: ...

    def append(self, arg: ContactResult, /) -> None: ...

    def clear(self) -> None: ...

class ContactResultMap:
    def __init__(self) -> None: ...

    def count(self) -> int: ...

    def size(self) -> int: ...

    def empty(self) -> bool: ...

    def clear(self) -> None: ...

    def release(self) -> None: ...

    def getSummary(self) -> str: ...

    def flattenCopyResults(self) -> ContactResultVector: ...

    def flattenMoveResults(self, results: ContactResultVector) -> None: ...

    def __len__(self) -> int: ...

class ContactTrajectorySubstepResults:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, substep: int, start_state: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], end_state: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]) -> None: ...

    @overload
    def __init__(self, substep: int, state: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]) -> None: ...

    def __bool__(self) -> bool: ...

    def addContact(self, substep_number: int, start_substate: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], end_substate: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], new_contacts: ContactResultMap) -> None: ...

    def numContacts(self) -> int: ...

    def worstCollision(self) -> ContactResultVector: ...

    @property
    def contacts(self) -> ContactResultMap: ...

    @contacts.setter
    def contacts(self, arg: ContactResultMap, /) -> None: ...

    @property
    def substep(self) -> int: ...

    @substep.setter
    def substep(self, arg: int, /) -> None: ...

    @property
    def state0(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    @state0.setter
    def state0(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], /) -> None: ...

    @property
    def state1(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    @state1.setter
    def state1(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], /) -> None: ...

class ContactTrajectoryStepResults:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, step_number: int, start_state: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], end_state: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], num_substeps: int) -> None: ...

    @overload
    def __init__(self, step_number: int, state: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]) -> None: ...

    def __bool__(self) -> bool: ...

    def addContact(self, step_number: int, substep_number: int, num_substeps: int, start_state: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], end_state: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], start_substate: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], end_substate: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], contacts: ContactResultMap) -> None: ...

    def resize(self, num_substeps: int) -> None: ...

    def numSubsteps(self) -> int: ...

    def numContacts(self) -> int: ...

    def worstSubstep(self) -> ContactTrajectorySubstepResults: ...

    def worstCollision(self) -> ContactResultVector: ...

    def mostCollisionsSubstep(self) -> ContactTrajectorySubstepResults: ...

    @property
    def substeps(self) -> list[ContactTrajectorySubstepResults]: ...

    @substeps.setter
    def substeps(self, arg: Sequence[ContactTrajectorySubstepResults], /) -> None: ...

    @property
    def step(self) -> int: ...

    @step.setter
    def step(self, arg: int, /) -> None: ...

    @property
    def state0(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    @state0.setter
    def state0(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], /) -> None: ...

    @property
    def state1(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    @state1.setter
    def state1(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], /) -> None: ...

    @property
    def total_substeps(self) -> int: ...

    @total_substeps.setter
    def total_substeps(self, arg: int, /) -> None: ...

class ContactTrajectoryResults:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, j_names: Sequence[str]) -> None: ...

    @overload
    def __init__(self, j_names: Sequence[str], num_steps: int) -> None: ...

    def __bool__(self) -> bool: ...

    def addContact(self, step_number: int, substep_number: int, num_substeps: int, start_state: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], end_state: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], start_substate: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], end_substate: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], contacts: ContactResultMap) -> None: ...

    def resize(self, num_steps: int) -> None: ...

    def numSteps(self) -> int: ...

    def numContacts(self) -> int: ...

    def worstStep(self) -> ContactTrajectoryStepResults: ...

    def worstCollision(self) -> ContactResultVector: ...

    def mostCollisionsStep(self) -> ContactTrajectoryStepResults: ...

    def trajectoryCollisionResultsTable(self) -> str: ...

    def collisionFrequencyPerLink(self) -> str: ...

    def condensedSummary(self) -> str: ...

    @property
    def steps(self) -> list[ContactTrajectoryStepResults]: ...

    @steps.setter
    def steps(self, arg: Sequence[ContactTrajectoryStepResults], /) -> None: ...

    @property
    def joint_names(self) -> list[str]: ...

    @joint_names.setter
    def joint_names(self, arg: Sequence[str], /) -> None: ...

    @property
    def total_steps(self) -> int: ...

    @total_steps.setter
    def total_steps(self, arg: int, /) -> None: ...

class ContactRequest:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, type: ContactTestType) -> None: ...

    @property
    def type(self) -> ContactTestType: ...

    @type.setter
    def type(self, arg: ContactTestType, /) -> None: ...

    @property
    def calculate_penetration(self) -> bool: ...

    @calculate_penetration.setter
    def calculate_penetration(self, arg: bool, /) -> None: ...

    @property
    def calculate_distance(self) -> bool: ...

    @calculate_distance.setter
    def calculate_distance(self, arg: bool, /) -> None: ...

    @property
    def contact_limit(self) -> int: ...

    @contact_limit.setter
    def contact_limit(self, arg: int, /) -> None: ...

class ContactManagerConfig:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, default_margin: float) -> None: ...

    @property
    def default_margin(self) -> float | None: ...

    @default_margin.setter
    def default_margin(self, arg: float, /) -> None: ...

    @property
    def pair_margin_override_type(self) -> tesseract_robotics.tesseract_common._tesseract_common.CollisionMarginPairOverrideType: ...

    @pair_margin_override_type.setter
    def pair_margin_override_type(self, arg: tesseract_robotics.tesseract_common._tesseract_common.CollisionMarginPairOverrideType, /) -> None: ...

    @property
    def pair_margin_data(self) -> tesseract_robotics.tesseract_common._tesseract_common.CollisionMarginPairData: ...

    @pair_margin_data.setter
    def pair_margin_data(self, arg: tesseract_robotics.tesseract_common._tesseract_common.CollisionMarginPairData, /) -> None: ...

    @property
    def acm(self) -> tesseract_robotics.tesseract_common._tesseract_common.AllowedCollisionMatrix: ...

    @acm.setter
    def acm(self, arg: tesseract_robotics.tesseract_common._tesseract_common.AllowedCollisionMatrix, /) -> None: ...

    @property
    def acm_override_type(self) -> ACMOverrideType: ...

    @acm_override_type.setter
    def acm_override_type(self, arg: ACMOverrideType, /) -> None: ...

    @property
    def modify_object_enabled(self) -> dict[str, bool]: ...

    @modify_object_enabled.setter
    def modify_object_enabled(self, arg: Mapping[str, bool], /) -> None: ...

    def incrementMargins(self, increment: float) -> None: ...

    def scaleMargins(self, scale: float) -> None: ...

    def validate(self) -> None: ...

    @property
    def margin_data_override_type(self) -> tesseract_robotics.tesseract_common._tesseract_common.CollisionMarginPairOverrideType: ...

    @margin_data_override_type.setter
    def margin_data_override_type(self, arg: tesseract_robotics.tesseract_common._tesseract_common.CollisionMarginPairOverrideType, /) -> None: ...

class CollisionCheckConfig:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, contact_request: ContactRequest = ..., type: CollisionEvaluatorType = CollisionEvaluatorType.DISCRETE, longest_valid_segment_length: float = 0.005, check_program_mode: CollisionCheckProgramType = CollisionCheckProgramType.ALL, exit_condition: CollisionCheckExitType = CollisionCheckExitType.FIRST) -> None: ...

    @property
    def contact_request(self) -> ContactRequest: ...

    @contact_request.setter
    def contact_request(self, arg: ContactRequest, /) -> None: ...

    @property
    def type(self) -> CollisionEvaluatorType: ...

    @type.setter
    def type(self, arg: CollisionEvaluatorType, /) -> None: ...

    @property
    def longest_valid_segment_length(self) -> float: ...

    @longest_valid_segment_length.setter
    def longest_valid_segment_length(self, arg: float, /) -> None: ...

    @property
    def check_program_mode(self) -> CollisionCheckProgramType: ...

    @check_program_mode.setter
    def check_program_mode(self, arg: CollisionCheckProgramType, /) -> None: ...

    @property
    def exit_condition(self) -> CollisionCheckExitType: ...

    @exit_condition.setter
    def exit_condition(self, arg: CollisionCheckExitType, /) -> None: ...

class DiscreteContactManager:
    def getName(self) -> str: ...

    def hasCollisionObject(self, name: str) -> bool: ...

    def removeCollisionObject(self, name: str) -> bool: ...

    def enableCollisionObject(self, name: str) -> bool: ...

    def disableCollisionObject(self, name: str) -> bool: ...

    def isCollisionObjectEnabled(self, name: str) -> bool: ...

    @overload
    def setCollisionObjectsTransform(self, name: str, pose: tesseract_robotics.tesseract_common._tesseract_common.Isometry3d) -> None: ...

    @overload
    def setCollisionObjectsTransform(self, names: Sequence[str], poses: Sequence[tesseract_robotics.tesseract_common._tesseract_common.Isometry3d]) -> None: ...

    @overload
    def setCollisionObjectsTransform(self, transforms: Mapping[str, tesseract_robotics.tesseract_common._tesseract_common.Isometry3d]) -> None: ...

    @overload
    def setCollisionObjectsTransform(self, transforms: Mapping[str, tesseract_robotics.tesseract_common._tesseract_common.Isometry3d]) -> None: ...

    def getCollisionObjects(self) -> list[str]: ...

    def setActiveCollisionObjects(self, names: Sequence[str]) -> None: ...

    def getActiveCollisionObjects(self) -> list[str]: ...

    def setDefaultCollisionMargin(self, default_collision_margin: float) -> None: ...

    def setCollisionMarginPair(self, name1: str, name2: str, collision_margin: float) -> None: ...

    def setCollisionMarginData(self, collision_margin_data: tesseract_robotics.tesseract_common._tesseract_common.CollisionMarginData) -> None: ...

    def setCollisionMarginPairData(self, pair_margin_data: tesseract_robotics.tesseract_common._tesseract_common.CollisionMarginPairData, override_type: tesseract_robotics.tesseract_common._tesseract_common.CollisionMarginPairOverrideType = tesseract_robotics.tesseract_common._tesseract_common.CollisionMarginPairOverrideType.REPLACE) -> None: ...

    def incrementCollisionMargin(self, increment: float) -> None: ...

    def setContactAllowedValidator(self, validator: tesseract_robotics.tesseract_common._tesseract_common.ContactAllowedValidator) -> None: ...

    def getContactAllowedValidator(self) -> tesseract_robotics.tesseract_common._tesseract_common.ContactAllowedValidator: ...

    def applyContactManagerConfig(self, config: ContactManagerConfig) -> None: ...

    def setDefaultCollisionMarginData(self, default_collision_margin: float) -> None: ...

    def setPairCollisionMarginData(self, name1: str, name2: str, collision_margin: float) -> None: ...

    def getCollisionMarginData(self) -> tesseract_robotics.tesseract_common._tesseract_common.CollisionMarginData: ...

    def addCollisionObject(self, name: str, mask_id: int, shapes: Sequence["tesseract::geometry::Geometry"], shape_poses: Sequence[tesseract_robotics.tesseract_common._tesseract_common.Isometry3d], enabled: bool = True) -> bool: ...

    def getCollisionObjectGeometries(self, name: str) -> list["tesseract::geometry::Geometry"]: ...

    def getCollisionObjectGeometriesTransforms(self, name: str) -> list[tesseract_robotics.tesseract_common._tesseract_common.Isometry3d]: ...

    def contactTest(self, collisions: ContactResultMap, request: ContactRequest) -> None: ...

    def clone(self) -> DiscreteContactManager: ...

class ContinuousContactManager:
    def getName(self) -> str: ...

    def hasCollisionObject(self, name: str) -> bool: ...

    def removeCollisionObject(self, name: str) -> bool: ...

    def enableCollisionObject(self, name: str) -> bool: ...

    def disableCollisionObject(self, name: str) -> bool: ...

    def isCollisionObjectEnabled(self, name: str) -> bool: ...

    def addCollisionObject(self, name: str, mask_id: int, shapes: Sequence["tesseract::geometry::Geometry"], shape_poses: Sequence[tesseract_robotics.tesseract_common._tesseract_common.Isometry3d], enabled: bool = True) -> bool: ...

    def getCollisionObjectGeometries(self, name: str) -> list["tesseract::geometry::Geometry"]: ...

    def getCollisionObjectGeometriesTransforms(self, name: str) -> list[tesseract_robotics.tesseract_common._tesseract_common.Isometry3d]: ...

    @overload
    def setCollisionObjectsTransform(self, name: str, pose: tesseract_robotics.tesseract_common._tesseract_common.Isometry3d) -> None: ...

    @overload
    def setCollisionObjectsTransform(self, names: Sequence[str], poses: Sequence[tesseract_robotics.tesseract_common._tesseract_common.Isometry3d]) -> None: ...

    @overload
    def setCollisionObjectsTransform(self, transforms: Mapping[str, tesseract_robotics.tesseract_common._tesseract_common.Isometry3d]) -> None: ...

    @overload
    def setCollisionObjectsTransformCast(self, name: str, pose1: tesseract_robotics.tesseract_common._tesseract_common.Isometry3d, pose2: tesseract_robotics.tesseract_common._tesseract_common.Isometry3d) -> None: ...

    @overload
    def setCollisionObjectsTransformCast(self, names: Sequence[str], pose1: Sequence[tesseract_robotics.tesseract_common._tesseract_common.Isometry3d], pose2: Sequence[tesseract_robotics.tesseract_common._tesseract_common.Isometry3d]) -> None: ...

    @overload
    def setCollisionObjectsTransformCast(self, pose1: Mapping[str, tesseract_robotics.tesseract_common._tesseract_common.Isometry3d], pose2: Mapping[str, tesseract_robotics.tesseract_common._tesseract_common.Isometry3d]) -> None: ...

    def getCollisionObjects(self) -> list[str]: ...

    def setActiveCollisionObjects(self, names: Sequence[str]) -> None: ...

    def getActiveCollisionObjects(self) -> list[str]: ...

    def setCollisionMarginData(self, collision_margin_data: tesseract_robotics.tesseract_common._tesseract_common.CollisionMarginData) -> None: ...

    def getCollisionMarginData(self) -> tesseract_robotics.tesseract_common._tesseract_common.CollisionMarginData: ...

    def setDefaultCollisionMargin(self, default_collision_margin: float) -> None: ...

    def setCollisionMarginPair(self, name1: str, name2: str, collision_margin: float) -> None: ...

    def setCollisionMarginPairData(self, pair_margin_data: tesseract_robotics.tesseract_common._tesseract_common.CollisionMarginPairData, override_type: tesseract_robotics.tesseract_common._tesseract_common.CollisionMarginPairOverrideType = tesseract_robotics.tesseract_common._tesseract_common.CollisionMarginPairOverrideType.REPLACE) -> None: ...

    def incrementCollisionMargin(self, increment: float) -> None: ...

    def setContactAllowedValidator(self, validator: tesseract_robotics.tesseract_common._tesseract_common.ContactAllowedValidator) -> None: ...

    def getContactAllowedValidator(self) -> tesseract_robotics.tesseract_common._tesseract_common.ContactAllowedValidator: ...

    def applyContactManagerConfig(self, config: ContactManagerConfig) -> None: ...

    def setDefaultCollisionMarginData(self, default_collision_margin: float) -> None: ...

    def setPairCollisionMarginData(self, name1: str, name2: str, collision_margin: float) -> None: ...

    def contactTest(self, collisions: ContactResultMap, request: ContactRequest) -> None: ...

    def clone(self) -> ContinuousContactManager: ...

class ContactManagersPluginFactory:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, config_path: tesseract_robotics.tesseract_common._tesseract_common.FilesystemPath, locator: tesseract_robotics.tesseract_common._tesseract_common.ResourceLocator) -> None: ...

    @overload
    def __init__(self, config: str, locator: tesseract_robotics.tesseract_common._tesseract_common.ResourceLocator) -> None: ...

    def addSearchPath(self, path: str) -> None: ...

    def getSearchPaths(self) -> list[str]: ...

    def addSearchLibrary(self, library_name: str) -> None: ...

    def getSearchLibraries(self) -> list[str]: ...

    def hasDiscreteContactManagerPlugins(self) -> bool: ...

    def getDefaultDiscreteContactManagerPlugin(self) -> str: ...

    def hasContinuousContactManagerPlugins(self) -> bool: ...

    def getDefaultContinuousContactManagerPlugin(self) -> str: ...

    def createDiscreteContactManager(self, name: str) -> DiscreteContactManager: ...

    def createContinuousContactManager(self, name: str) -> ContinuousContactManager: ...

def makeConvexMesh(mesh: "tesseract::geometry::Mesh") -> "tesseract::geometry::ConvexMesh":
    """Create a ConvexMesh from a Mesh using bullet's convex hull algorithm"""
