/PROG  SPIKE
/ATTR
OWNER		= MNEDITOR;
COMMENT		= "tesseract emitters";
PROG_SIZE	= 0;
CREATE		= DATE 31-12-14  TIME 12:00:00;
MODIFIED	= DATE 31-12-14  TIME 12:00:00;
FILE_NAME	= SPIKE;
VERSION		= 0;
LINE_COUNT	= 8;
MEMORY_SIZE	= 0;
PROTECT		= READ_WRITE;
TCD:  STACK_SIZE	= 0,
      TASK_PRIORITY	= 50,
      TIME_SLICE	= 0,
      BUSY_LAMP_OFF	= 0,
      ABORT_REQUEST	= 0,
      PAUSE_REQUEST	= 0;
DEFAULT_GROUP	= 1,*,*,*,*,*,*;
CONTROL_CODE	= 00000000 00000000;
/MN
   1:! generated by tesseract_robotics.emitters <VERSION>
   2:! ir-digest: sha256:c2a38edca8d365459846cff61786ff839fd14b4a2cc5da46fa82028e21ca6a20 ;
   3:! profiles-digest: sha256:9eb5ee08ae2c01eec262ef5f0a1c2b838bdbdccd79c728b46dfcb4f9663ec613 ;
   4:! DO NOT EDIT — regenerate from the planning pipeline ;
   5:J P[1] 100% FINE ;
   6:J P[2] 100% FINE ;
   7:L P[3] 100mm/sec FINE ;
   8:L P[4] 100mm/sec FINE ;
/POS
P[1]{
   GP1:
	UF : 0, UT : 1,
	J1 = 0.000 deg, J2 = -20.000 deg, J3 = 30.000 deg,
	J4 = 0.000 deg, J5 = 50.000 deg, J6 = 0.000 deg
};
P[2]{
   GP1:
	UF : 0, UT : 1,
	J1 = 30.000 deg, J2 = 10.000 deg, J3 = 15.000 deg,
	J4 = 20.000 deg, J5 = 40.000 deg, J6 = -10.000 deg
};
P[3]{
   GP1:
	UF : 0, UT : 1,		CONFIG : 'N U T, 0, 0, 0',
	X = 600.000 mm, Y = -100.000 mm, Z = 800.000 mm,
	W = 180.000 deg, P = 0.000 deg, R = 0.000 deg
};
P[4]{
   GP1:
	UF : 0, UT : 1,		CONFIG : 'N U T, 0, 0, 0',
	X = 600.000 mm, Y = -20.000 mm, Z = 800.000 mm,
	W = 180.000 deg, P = 0.000 deg, R = 0.000 deg
};
/END
