import enum
from collections.abc import Sequence
from typing import Annotated, overload

import numpy
from numpy.typing import NDArray

import tesseract_robotics.tesseract_geometry._tesseract_geometry

class JointType(enum.Enum):
    UNKNOWN = 0

    REVOLUTE = 1

    CONTINUOUS = 2

    PRISMATIC = 3

    FLOATING = 4

    PLANAR = 5

    FIXED = 6

JointType_UNKNOWN: JointType = JointType.UNKNOWN

JointType_REVOLUTE: JointType = JointType.REVOLUTE

JointType_CONTINUOUS: JointType = JointType.CONTINUOUS

JointType_PRISMATIC: JointType = JointType.PRISMATIC

JointType_FLOATING: JointType = JointType.FLOATING

JointType_PLANAR: JointType = JointType.PLANAR

JointType_FIXED: JointType = JointType.FIXED

class JointDynamics:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, damping: float, friction: float) -> None: ...
    @property
    def damping(self) -> float: ...
    @damping.setter
    def damping(self, arg: float, /) -> None: ...
    @property
    def friction(self) -> float: ...
    @friction.setter
    def friction(self, arg: float, /) -> None: ...
    def clear(self) -> None: ...
    def __eq__(self, arg: JointDynamics, /) -> bool: ...
    def __ne__(self, arg: JointDynamics, /) -> bool: ...
    def __repr__(self) -> str: ...

class JointLimits:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self,
        lower: float,
        upper: float,
        effort: float,
        velocity: float,
        acceleration: float,
        jerk: float,
    ) -> None: ...
    @property
    def lower(self) -> float: ...
    @lower.setter
    def lower(self, arg: float, /) -> None: ...
    @property
    def upper(self) -> float: ...
    @upper.setter
    def upper(self, arg: float, /) -> None: ...
    @property
    def effort(self) -> float: ...
    @effort.setter
    def effort(self, arg: float, /) -> None: ...
    @property
    def velocity(self) -> float: ...
    @velocity.setter
    def velocity(self, arg: float, /) -> None: ...
    @property
    def acceleration(self) -> float: ...
    @acceleration.setter
    def acceleration(self, arg: float, /) -> None: ...
    @property
    def jerk(self) -> float: ...
    @jerk.setter
    def jerk(self, arg: float, /) -> None: ...
    def clear(self) -> None: ...
    def __eq__(self, arg: JointLimits, /) -> bool: ...
    def __ne__(self, arg: JointLimits, /) -> bool: ...
    def __repr__(self) -> str: ...

class JointSafety:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self, soft_upper_limit: float, soft_lower_limit: float, k_position: float, k_velocity: float
    ) -> None: ...
    @property
    def soft_upper_limit(self) -> float: ...
    @soft_upper_limit.setter
    def soft_upper_limit(self, arg: float, /) -> None: ...
    @property
    def soft_lower_limit(self) -> float: ...
    @soft_lower_limit.setter
    def soft_lower_limit(self, arg: float, /) -> None: ...
    @property
    def k_position(self) -> float: ...
    @k_position.setter
    def k_position(self, arg: float, /) -> None: ...
    @property
    def k_velocity(self) -> float: ...
    @k_velocity.setter
    def k_velocity(self, arg: float, /) -> None: ...
    def clear(self) -> None: ...
    def __eq__(self, arg: JointSafety, /) -> bool: ...
    def __ne__(self, arg: JointSafety, /) -> bool: ...

class JointCalibration:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, reference_position: float, rising: float, falling: float) -> None: ...
    @property
    def reference_position(self) -> float: ...
    @reference_position.setter
    def reference_position(self, arg: float, /) -> None: ...
    @property
    def rising(self) -> float: ...
    @rising.setter
    def rising(self, arg: float, /) -> None: ...
    @property
    def falling(self) -> float: ...
    @falling.setter
    def falling(self, arg: float, /) -> None: ...
    def clear(self) -> None: ...
    def __eq__(self, arg: JointCalibration, /) -> bool: ...
    def __ne__(self, arg: JointCalibration, /) -> bool: ...

class JointMimic:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, offset: float, multiplier: float, joint_name: str) -> None: ...
    @property
    def offset(self) -> float: ...
    @offset.setter
    def offset(self, arg: float, /) -> None: ...
    @property
    def multiplier(self) -> float: ...
    @multiplier.setter
    def multiplier(self, arg: float, /) -> None: ...
    @property
    def joint_name(self) -> str: ...
    @joint_name.setter
    def joint_name(self, arg: str, /) -> None: ...
    def clear(self) -> None: ...
    def __eq__(self, arg: JointMimic, /) -> bool: ...
    def __ne__(self, arg: JointMimic, /) -> bool: ...

class Joint:
    @overload
    def __init__(self, name: str) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def getName(self) -> str: ...
    @property
    def type(self) -> JointType: ...
    @type.setter
    def type(self, arg: JointType, /) -> None: ...
    @property
    def axis(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order="C")]: ...
    @axis.setter
    def axis(
        self, arg: Annotated[NDArray[numpy.float64], dict(shape=(3), order="C")], /
    ) -> None: ...
    @property
    def child_link_name(self) -> str: ...
    @child_link_name.setter
    def child_link_name(self, arg: str, /) -> None: ...
    @property
    def parent_link_name(self) -> str: ...
    @parent_link_name.setter
    def parent_link_name(self, arg: str, /) -> None: ...
    @property
    def parent_to_joint_origin_transform(self) -> "Eigen::Transform<double, 3, 1, 0>": ...
    @parent_to_joint_origin_transform.setter
    def parent_to_joint_origin_transform(
        self, arg: "Eigen::Transform<double, 3, 1, 0>", /
    ) -> None: ...
    @property
    def dynamics(self) -> JointDynamics: ...
    @dynamics.setter
    def dynamics(self, arg: JointDynamics, /) -> None: ...
    @property
    def limits(self) -> JointLimits: ...
    @limits.setter
    def limits(self, arg: JointLimits, /) -> None: ...
    @property
    def safety(self) -> JointSafety: ...
    @safety.setter
    def safety(self, arg: JointSafety, /) -> None: ...
    @property
    def calibration(self) -> JointCalibration: ...
    @calibration.setter
    def calibration(self, arg: JointCalibration, /) -> None: ...
    @property
    def mimic(self) -> JointMimic: ...
    @mimic.setter
    def mimic(self, arg: JointMimic, /) -> None: ...
    def clear(self) -> None: ...
    @overload
    def clone(self) -> Joint: ...
    @overload
    def clone(self, name: str) -> Joint: ...
    def __eq__(self, arg: Joint, /) -> bool: ...
    def __ne__(self, arg: Joint, /) -> bool: ...
    def __repr__(self) -> str: ...

class Material:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, name: str) -> None: ...
    def getName(self) -> str: ...
    @property
    def texture_filename(self) -> str: ...
    @texture_filename.setter
    def texture_filename(self, arg: str, /) -> None: ...
    @property
    def color(self) -> Annotated[NDArray[numpy.float64], dict(shape=(4), order="C")]: ...
    @color.setter
    def color(
        self, arg: Annotated[NDArray[numpy.float64], dict(shape=(4), order="C")], /
    ) -> None: ...
    @staticmethod
    def getDefaultMaterial() -> Material: ...
    def clear(self) -> None: ...
    def __eq__(self, arg: Material, /) -> bool: ...
    def __ne__(self, arg: Material, /) -> bool: ...

class Inertial:
    def __init__(self) -> None: ...
    @property
    def origin(self) -> "Eigen::Transform<double, 3, 1, 0>": ...
    @origin.setter
    def origin(self, arg: "Eigen::Transform<double, 3, 1, 0>", /) -> None: ...
    @property
    def mass(self) -> float: ...
    @mass.setter
    def mass(self, arg: float, /) -> None: ...
    @property
    def ixx(self) -> float: ...
    @ixx.setter
    def ixx(self, arg: float, /) -> None: ...
    @property
    def ixy(self) -> float: ...
    @ixy.setter
    def ixy(self, arg: float, /) -> None: ...
    @property
    def ixz(self) -> float: ...
    @ixz.setter
    def ixz(self, arg: float, /) -> None: ...
    @property
    def iyy(self) -> float: ...
    @iyy.setter
    def iyy(self, arg: float, /) -> None: ...
    @property
    def iyz(self) -> float: ...
    @iyz.setter
    def iyz(self, arg: float, /) -> None: ...
    @property
    def izz(self) -> float: ...
    @izz.setter
    def izz(self, arg: float, /) -> None: ...
    def clear(self) -> None: ...
    def __eq__(self, arg: Inertial, /) -> bool: ...
    def __ne__(self, arg: Inertial, /) -> bool: ...

class Visual:
    def __init__(self) -> None: ...
    @property
    def origin(self) -> "Eigen::Transform<double, 3, 1, 0>": ...
    @origin.setter
    def origin(self, arg: "Eigen::Transform<double, 3, 1, 0>", /) -> None: ...
    @property
    def geometry(self) -> tesseract_robotics.tesseract_geometry._tesseract_geometry.Geometry: ...
    @geometry.setter
    def geometry(
        self, arg: tesseract_robotics.tesseract_geometry._tesseract_geometry.Geometry, /
    ) -> None: ...
    @property
    def material(self) -> Material: ...
    @material.setter
    def material(self, arg: Material, /) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, arg: str, /) -> None: ...
    def clear(self) -> None: ...
    def __eq__(self, arg: Visual, /) -> bool: ...
    def __ne__(self, arg: Visual, /) -> bool: ...

class Collision:
    def __init__(self) -> None: ...
    @property
    def origin(self) -> "Eigen::Transform<double, 3, 1, 0>": ...
    @origin.setter
    def origin(self, arg: "Eigen::Transform<double, 3, 1, 0>", /) -> None: ...
    @property
    def geometry(self) -> tesseract_robotics.tesseract_geometry._tesseract_geometry.Geometry: ...
    @geometry.setter
    def geometry(
        self, arg: tesseract_robotics.tesseract_geometry._tesseract_geometry.Geometry, /
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, arg: str, /) -> None: ...
    def clear(self) -> None: ...
    def __eq__(self, arg: Collision, /) -> bool: ...
    def __ne__(self, arg: Collision, /) -> bool: ...

class Link:
    @overload
    def __init__(self, name: str) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def getName(self) -> str: ...
    @property
    def inertial(self) -> Inertial: ...
    @inertial.setter
    def inertial(self, arg: Inertial, /) -> None: ...
    @property
    def visual(self) -> list[Visual]: ...
    @visual.setter
    def visual(self, arg: Sequence[Visual], /) -> None: ...
    @property
    def collision(self) -> list[Collision]: ...
    @collision.setter
    def collision(self, arg: Sequence[Collision], /) -> None: ...
    def addVisual(self, visual: Visual) -> None:
        """Add a Visual to this link"""

    def addCollision(self, collision: Collision) -> None:
        """Add a Collision to this link"""

    def clearVisual(self) -> None:
        """Clear all Visual elements from this link"""

    def clearCollision(self) -> None:
        """Clear all Collision elements from this link"""

    def clear(self) -> None: ...
    @overload
    def clone(self) -> Link: ...
    @overload
    def clone(self, name: str) -> Link: ...
    def __eq__(self, arg: Link, /) -> bool: ...
    def __ne__(self, arg: Link, /) -> bool: ...
    def __repr__(self) -> str: ...

class ShortestPath:
    def __init__(self) -> None: ...
    @property
    def links(self) -> list[str]: ...
    @links.setter
    def links(self, arg: Sequence[str], /) -> None: ...
    @property
    def joints(self) -> list[str]: ...
    @joints.setter
    def joints(self, arg: Sequence[str], /) -> None: ...
    @property
    def active_joints(self) -> list[str]: ...
    @active_joints.setter
    def active_joints(self, arg: Sequence[str], /) -> None: ...

class SceneGraph:
    def __init__(self, name: str = "") -> None: ...
    def clone(self) -> SceneGraph: ...
    def clear(self) -> None: ...
    def setName(self, name: str) -> None: ...
    def getName(self) -> str: ...
    def setRoot(self, name: str) -> bool: ...
    def getRoot(self) -> str: ...
    @overload
    def addLink(self, link: Link, replace_allowed: bool = False) -> bool: ...
    @overload
    def addLink(self, link: Link, joint: Joint) -> bool: ...
    def getLink(self, name: str) -> Link: ...
    def getLinks(self) -> list[Link]: ...
    def getLeafLinks(self) -> list[Link]: ...
    def removeLink(self, name: str, recursive: bool = False) -> bool: ...
    def moveLink(self, joint: Joint) -> bool: ...
    def setLinkVisibility(self, name: str, visibility: bool) -> None: ...
    def getLinkVisibility(self, name: str) -> bool: ...
    def setLinkCollisionEnabled(self, name: str, enabled: bool) -> None: ...
    def getLinkCollisionEnabled(self, name: str) -> bool: ...
    def addJoint(self, joint: Joint) -> bool: ...
    def getJoint(self, name: str) -> Joint: ...
    def removeJoint(self, name: str, recursive: bool = False) -> bool: ...
    def moveJoint(self, name: str, parent_link: str) -> bool: ...
    def getJoints(self) -> list[Joint]: ...
    def getActiveJoints(self) -> list[Joint]: ...
    def changeJointOrigin(
        self, name: str, new_origin: "Eigen::Transform<double, 3, 1, 0>"
    ) -> bool: ...
    def changeJointLimits(self, name: str, limits: JointLimits) -> bool: ...
    def changeJointPositionLimits(self, name: str, lower: float, upper: float) -> bool: ...
    def changeJointVelocityLimits(self, name: str, limit: float) -> bool: ...
    def changeJointAccelerationLimits(self, name: str, limit: float) -> bool: ...
    def changeJointJerkLimits(self, name: str, limit: float) -> bool: ...
    def getJointLimits(self, name: str) -> JointLimits: ...
    def addAllowedCollision(self, link_name1: str, link_name2: str, reason: str) -> None: ...
    @overload
    def removeAllowedCollision(self, link_name1: str, link_name2: str) -> None: ...
    @overload
    def removeAllowedCollision(self, link_name: str) -> None: ...
    def clearAllowedCollisions(self) -> None: ...
    def isCollisionAllowed(self, link_name1: str, link_name2: str) -> bool: ...
    def getAllowedCollisionMatrix(self) -> "tesseract_common::AllowedCollisionMatrix":
        """Get the allowed collision matrix"""

    def getSourceLink(self, joint_name: str) -> Link: ...
    def getTargetLink(self, joint_name: str) -> Link: ...
    def getInboundJoints(self, link_name: str) -> list[Joint]: ...
    def getOutboundJoints(self, link_name: str) -> list[Joint]: ...
    def isAcyclic(self) -> bool: ...
    def isTree(self) -> bool: ...
    def isEmpty(self) -> bool: ...
    def getAdjacentLinkNames(self, name: str) -> list[str]: ...
    def getInvAdjacentLinkNames(self, name: str) -> list[str]: ...
    def getLinkChildrenNames(self, name: str) -> list[str]: ...
    def getJointChildrenNames(self, name: str) -> list[str]: ...
    def getShortestPath(self, root: str, tip: str) -> ShortestPath: ...
    def saveDOT(self, path: str) -> None: ...
    @overload
    def insertSceneGraph(self, scene_graph: SceneGraph, prefix: str = "") -> bool: ...
    @overload
    def insertSceneGraph(self, scene_graph: SceneGraph, joint: Joint, prefix: str = "") -> bool: ...
    def __eq__(self, arg: SceneGraph, /) -> bool: ...
    def __ne__(self, arg: SceneGraph, /) -> bool: ...
    def __repr__(self) -> str: ...
