from typing import Annotated, overload

import numpy
from numpy.typing import NDArray

import tesseract_robotics.tesseract_command_language._tesseract_command_language


class InstructionsTrajectory:
    def __init__(self, program: tesseract_robotics.tesseract_command_language._tesseract_command_language.CompositeInstruction) -> None: ...

    def getPosition(self, i: int) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    def getVelocity(self, i: int) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    def getAcceleration(self, i: int) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    def getTimeFromStart(self, i: int) -> float: ...

    def setData(self, i: int, velocity: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], acceleration: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], time: float) -> None: ...

    def size(self) -> int: ...

    def dof(self) -> int: ...

    def empty(self) -> bool: ...

    def isTimeStrictlyIncreasing(self) -> bool: ...

class TOTGCompositeProfile(tesseract_robotics.tesseract_command_language._tesseract_command_language.Profile):
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, max_velocity_scaling_factor: float, max_acceleration_scaling_factor: float, path_tolerance: float, min_angle_change: float) -> None: ...

    @staticmethod
    def getStaticKey() -> int: ...

    @property
    def override_limits(self) -> bool: ...

    @override_limits.setter
    def override_limits(self, arg: bool, /) -> None: ...

    @property
    def velocity_limits(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='F')]: ...

    @velocity_limits.setter
    def velocity_limits(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='F')], /) -> None: ...

    @property
    def acceleration_limits(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='F')]: ...

    @acceleration_limits.setter
    def acceleration_limits(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='F')], /) -> None: ...

    @property
    def max_velocity_scaling_factor(self) -> float: ...

    @max_velocity_scaling_factor.setter
    def max_velocity_scaling_factor(self, arg: float, /) -> None: ...

    @property
    def max_acceleration_scaling_factor(self) -> float: ...

    @max_acceleration_scaling_factor.setter
    def max_acceleration_scaling_factor(self, arg: float, /) -> None: ...

    @property
    def path_tolerance(self) -> float: ...

    @path_tolerance.setter
    def path_tolerance(self, arg: float, /) -> None: ...

    @property
    def min_angle_change(self) -> float: ...

    @min_angle_change.setter
    def min_angle_change(self, arg: float, /) -> None: ...

class ISPCompositeProfile(tesseract_robotics.tesseract_command_language._tesseract_command_language.Profile):
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, max_velocity_scaling_factor: float, max_acceleration_scaling_factor: float) -> None: ...

    @staticmethod
    def getStaticKey() -> int: ...

    @property
    def add_points(self) -> bool: ...

    @add_points.setter
    def add_points(self, arg: bool, /) -> None: ...

    @property
    def override_limits(self) -> bool: ...

    @override_limits.setter
    def override_limits(self, arg: bool, /) -> None: ...

    @property
    def velocity_limits(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='F')]: ...

    @velocity_limits.setter
    def velocity_limits(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='F')], /) -> None: ...

    @property
    def acceleration_limits(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='F')]: ...

    @acceleration_limits.setter
    def acceleration_limits(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='F')], /) -> None: ...

    @property
    def max_velocity_scaling_factor(self) -> float: ...

    @max_velocity_scaling_factor.setter
    def max_velocity_scaling_factor(self, arg: float, /) -> None: ...

    @property
    def max_acceleration_scaling_factor(self) -> float: ...

    @max_acceleration_scaling_factor.setter
    def max_acceleration_scaling_factor(self, arg: float, /) -> None: ...

class ISPMoveProfile(tesseract_robotics.tesseract_command_language._tesseract_command_language.Profile):
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, max_velocity_scaling_factor: float, max_acceleration_scaling_factor: float) -> None: ...

    @staticmethod
    def getStaticKey() -> int: ...

    @property
    def max_velocity_scaling_factor(self) -> float: ...

    @max_velocity_scaling_factor.setter
    def max_velocity_scaling_factor(self, arg: float, /) -> None: ...

    @property
    def max_acceleration_scaling_factor(self) -> float: ...

    @max_acceleration_scaling_factor.setter
    def max_acceleration_scaling_factor(self, arg: float, /) -> None: ...

class TimeParameterization:
    def getName(self) -> str: ...

    def compute(self, composite_instruction: tesseract_robotics.tesseract_command_language._tesseract_command_language.CompositeInstruction, env: "tesseract_environment::Environment", profiles: tesseract_robotics.tesseract_command_language._tesseract_command_language.ProfileDictionary) -> bool: ...

class TimeOptimalTrajectoryGeneration(TimeParameterization):
    def __init__(self, name: str = 'TOTG') -> None: ...

class IterativeSplineParameterization(TimeParameterization):
    def __init__(self, name: str = 'ISP') -> None: ...
