"""End-to-end KRL emit golden (OUR emitter's output, hand-reviewed once).

The package-version line of the identity header is environment-dependent, so it
is normalized to ``<VERSION>`` in both golden and actual before comparison; the
two SHA-256 digest lines are content-stable and compared verbatim.
"""

from __future__ import annotations

import difflib
import re
from pathlib import Path

import numpy as np

from tesseract_robotics.emitters.krl import KrlProfile, emit_krl
from tesseract_robotics.planning import CartesianTarget, JointTarget, MotionProgram, Pose

GOLDEN = Path(__file__).parent / "golden" / "spike.src"
JOINT_NAMES = [f"joint_{i}" for i in range(1, 7)]
_VERSION_LINE = re.compile(r"(generated by tesseract_robotics\.emitters ).*")


def _normalize_version(text: str) -> str:
    return _VERSION_LINE.sub(r"\1<VERSION>", text)


def _spike_composite():
    prog = MotionProgram("manipulator", tcp_frame="tool0", profile="SPIKE")
    prog.move_to(JointTarget(np.deg2rad([0, -20, 30, 0, 50, 0]), profile="JMOVE"))
    prog.move_to(JointTarget(np.deg2rad([30, 10, 15, 20, 40, -10]), profile="JMOVE"))
    prog.linear_to(
        CartesianTarget(Pose.from_xyz_rpy([0.6, -0.1, 0.8], [np.pi, 0, 0]), profile="LMOVE")
    )
    prog.linear_to(
        CartesianTarget(Pose.from_xyz_rpy([0.6, -0.02, 0.8], [np.pi, 0, 0]), profile="LMOVE")
    )
    prog.set_joint_names(JOINT_NAMES)
    return prog.to_composite_instruction(joint_names=JOINT_NAMES, tcp_frame="tool0")


def _profiles():
    return {
        "JMOVE": KrlProfile.build(ptp_speed_percent=100.0),
        "LMOVE": KrlProfile.build(cp_speed_mms=100.0),
        "SPIKE": KrlProfile.build(),
        "DEFAULT": KrlProfile.build(),
        "cartesian_program": KrlProfile.build(),
        "freespace_profile": KrlProfile.build(),
    }


def test_emit_krl_matches_golden() -> None:
    actual = _normalize_version(
        emit_krl(_spike_composite(), _profiles(), program_name="SPIKE").text
    )
    expected = GOLDEN.read_text()
    diff = "\n".join(
        difflib.unified_diff(
            expected.splitlines(), actual.splitlines(), "golden", "emit_krl", lineterm=""
        )
    )
    assert actual == expected, f"diverged from golden:\n{diff}"
