from typing import Annotated, overload

import numpy
from numpy.typing import NDArray

class Bounds:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, lower: float, upper: float) -> None: ...
    @property
    def lower(self) -> float: ...
    @lower.setter
    def lower(self, arg: float, /) -> None: ...
    @property
    def upper(self) -> float: ...
    @upper.setter
    def upper(self, arg: float, /) -> None: ...
    def __iadd__(self, arg: float, /) -> Bounds: ...
    def __isub__(self, arg: float, /) -> Bounds: ...
    def __repr__(self) -> str: ...

inf: float = 1e20

NoBound: Bounds = ...

BoundZero: Bounds = ...

BoundGreaterZero: Bounds = ...

BoundSmallerZero: Bounds = ...

class Component:
    def GetValues(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order="C")]: ...
    def GetBounds(self) -> list[Bounds]: ...
    def SetVariables(
        self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None,), order="C")], /
    ) -> None: ...
    def GetJacobian(self) -> "Eigen::SparseMatrix<double, 1, int>": ...
    def GetRows(self) -> int: ...
    def GetName(self) -> str: ...
    def SetRows(self, arg: int, /) -> None: ...
    def Print(self, tolerance: float, index_start: int) -> None: ...

    kSpecifyLater: int = ...
    """(arg: object, /) -> int"""

class Composite(Component):
    def __init__(self, name: str, is_cost: bool) -> None: ...
    def GetValues(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order="C")]: ...
    def GetJacobian(self) -> "Eigen::SparseMatrix<double, 1, int>": ...
    def GetBounds(self) -> list[Bounds]: ...
    def SetVariables(
        self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None,), order="C")], /
    ) -> None: ...
    def PrintAll(self) -> None: ...
    def GetComponent(self, arg: str, /) -> Component: ...
    def AddComponent(self, arg: Component, /) -> None: ...
    def ClearComponents(self) -> None: ...
    def GetComponents(self) -> list[Component]: ...

class VariableSet(Component):
    def __init__(self, n_var: int, name: str) -> None: ...
    def GetValues(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order="C")]: ...
    def GetBounds(self) -> list[Bounds]: ...
    def SetVariables(
        self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None,), order="C")], /
    ) -> None: ...

class ConstraintSet(Component):
    def __init__(self, n_constraints: int, name: str) -> None: ...
    def GetValues(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order="C")]: ...
    def GetBounds(self) -> list[Bounds]: ...
    def GetJacobian(self) -> "Eigen::SparseMatrix<double, 1, int>": ...
    def LinkWithVariables(self, arg: Composite, /) -> None: ...
    def FillJacobianBlock(
        self, arg0: str, arg1: "Eigen::SparseMatrix<double, 1, int>", /
    ) -> None: ...

class CostTerm(ConstraintSet):
    def GetValues(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order="C")]: ...
    def GetBounds(self) -> list[Bounds]: ...
    def GetCost(self) -> float: ...
    def Print(self, tolerance: float, index: int) -> None: ...
