"""tesseract_environment Python bindings"""

from collections.abc import Callable, Mapping, Sequence
import datetime
import enum
import os
from typing import Annotated, overload

import numpy
from numpy.typing import NDArray

import tesseract_robotics.tesseract_collision._tesseract_collision
import tesseract_robotics.tesseract_common._tesseract_common
import tesseract_robotics.tesseract_kinematics._tesseract_kinematics
import tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph
import tesseract_robotics.tesseract_srdf._tesseract_srdf
import tesseract_robotics.tesseract_state_solver._tesseract_state_solver


class Events(enum.Enum):
    COMMAND_APPLIED = 0

    SCENE_STATE_CHANGED = 1

class Event:
    @property
    def type(self) -> Events: ...

class CommandAppliedEvent(Event):
    @property
    def commands(self) -> list[Command]: ...

    @property
    def revision(self) -> int: ...

class SceneStateChangedEvent(Event):
    @property
    def state(self) -> tesseract_robotics.tesseract_state_solver._tesseract_state_solver.SceneState: ...

class EventTypeError(TypeError):
    """
    cast_CommandAppliedEvent / cast_SceneStateChangedEvent got an event of the other type.
    """

def cast_CommandAppliedEvent(evt: Event) -> CommandAppliedEvent:
    """
    Downcast an Event to CommandAppliedEvent. Raises EventTypeError if evt.type is not COMMAND_APPLIED.
    """

def cast_SceneStateChangedEvent(evt: Event) -> SceneStateChangedEvent:
    """
    Downcast an Event to SceneStateChangedEvent. Raises EventTypeError if evt.type is not SCENE_STATE_CHANGED.
    """

@overload
def checkTrajectory(manager: tesseract_robotics.tesseract_collision._tesseract_collision.DiscreteContactManager, state_solver: tesseract_robotics.tesseract_state_solver._tesseract_state_solver.StateSolver, joint_names: Sequence[str], traj: Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='C')], config: tesseract_robotics.tesseract_collision._tesseract_collision.CollisionCheckConfig) -> tuple[tesseract_robotics.tesseract_collision._tesseract_collision.ContactTrajectoryResults, list[tesseract_robotics.tesseract_collision._tesseract_collision.ContactResultMap]]: ...

@overload
def checkTrajectory(manager: tesseract_robotics.tesseract_collision._tesseract_collision.DiscreteContactManager, manip: tesseract_robotics.tesseract_kinematics._tesseract_kinematics.JointGroup, traj: Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='C')], config: tesseract_robotics.tesseract_collision._tesseract_collision.CollisionCheckConfig) -> tuple[tesseract_robotics.tesseract_collision._tesseract_collision.ContactTrajectoryResults, list[tesseract_robotics.tesseract_collision._tesseract_collision.ContactResultMap]]: ...

@overload
def checkTrajectory(manager: tesseract_robotics.tesseract_collision._tesseract_collision.ContinuousContactManager, state_solver: tesseract_robotics.tesseract_state_solver._tesseract_state_solver.StateSolver, joint_names: Sequence[str], traj: Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='C')], config: tesseract_robotics.tesseract_collision._tesseract_collision.CollisionCheckConfig) -> tuple[tesseract_robotics.tesseract_collision._tesseract_collision.ContactTrajectoryResults, list[tesseract_robotics.tesseract_collision._tesseract_collision.ContactResultMap]]: ...

@overload
def checkTrajectory(manager: tesseract_robotics.tesseract_collision._tesseract_collision.ContinuousContactManager, manip: tesseract_robotics.tesseract_kinematics._tesseract_kinematics.JointGroup, traj: Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='C')], config: tesseract_robotics.tesseract_collision._tesseract_collision.CollisionCheckConfig) -> tuple[tesseract_robotics.tesseract_collision._tesseract_collision.ContactTrajectoryResults, list[tesseract_robotics.tesseract_collision._tesseract_collision.ContactResultMap]]: ...

def checkTrajectorySegment(manager: tesseract_robotics.tesseract_collision._tesseract_collision.ContinuousContactManager, state0: Mapping[str, tesseract_robotics.tesseract_common._tesseract_common.Isometry3d], state1: Mapping[str, tesseract_robotics.tesseract_common._tesseract_common.Isometry3d], contact_request: tesseract_robotics.tesseract_collision._tesseract_collision.ContactRequest) -> tesseract_robotics.tesseract_collision._tesseract_collision.ContactResultMap: ...

@overload
def checkTrajectoryState(manager: tesseract_robotics.tesseract_collision._tesseract_collision.DiscreteContactManager, state: Mapping[str, tesseract_robotics.tesseract_common._tesseract_common.Isometry3d], contact_request: tesseract_robotics.tesseract_collision._tesseract_collision.ContactRequest) -> tesseract_robotics.tesseract_collision._tesseract_collision.ContactResultMap: ...

@overload
def checkTrajectoryState(manager: tesseract_robotics.tesseract_collision._tesseract_collision.ContinuousContactManager, state: Mapping[str, tesseract_robotics.tesseract_common._tesseract_common.Isometry3d], contact_request: tesseract_robotics.tesseract_collision._tesseract_collision.ContactRequest) -> tesseract_robotics.tesseract_collision._tesseract_collision.ContactResultMap: ...

class EventCallbackFn:
    def __init__(self, callback: Callable) -> None: ...

class CommandType(enum.Enum):
    UNINITIALIZED = -1

    ADD_LINK = 0

    MOVE_LINK = 1

    MOVE_JOINT = 2

    REMOVE_LINK = 3

    REMOVE_JOINT = 4

    CHANGE_LINK_ORIGIN = 5

    CHANGE_JOINT_ORIGIN = 6

    CHANGE_LINK_COLLISION_ENABLED = 7

    CHANGE_LINK_VISIBILITY = 8

    MODIFY_ALLOWED_COLLISIONS = 9

    REMOVE_ALLOWED_COLLISION_LINK = 10

    ADD_SCENE_GRAPH = 11

    CHANGE_JOINT_POSITION_LIMITS = 12

    CHANGE_JOINT_VELOCITY_LIMITS = 13

    CHANGE_JOINT_ACCELERATION_LIMITS = 14

    ADD_KINEMATICS_INFORMATION = 15

    REPLACE_JOINT = 16

    CHANGE_COLLISION_MARGINS = 17

    ADD_CONTACT_MANAGERS_PLUGIN_INFO = 18

    SET_ACTIVE_DISCRETE_CONTACT_MANAGER = 19

    SET_ACTIVE_CONTINUOUS_CONTACT_MANAGER = 20

    ADD_TRAJECTORY_LINK = 21

class Command:
    def getType(self) -> CommandType: ...

class RemoveJointCommand(Command):
    def __init__(self, joint_name: str) -> None: ...

    def getJointName(self) -> str: ...

class AddLinkCommand(Command):
    @overload
    def __init__(self, link: tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.Link, replace_allowed: bool = False) -> None: ...

    @overload
    def __init__(self, link: tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.Link, joint: tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.Joint, replace_allowed: bool = False) -> None: ...

    def getLink(self) -> tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.Link: ...

    def getJoint(self) -> tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.Joint: ...

    def replaceAllowed(self) -> bool: ...

class RemoveLinkCommand(Command):
    def __init__(self, link_name: str) -> None: ...

    def getLinkName(self) -> str: ...

class AddSceneGraphCommand(Command):
    @overload
    def __init__(self, scene_graph: tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.SceneGraph, prefix: str = '') -> None: ...

    @overload
    def __init__(self, scene_graph: tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.SceneGraph, joint: tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.Joint, prefix: str = '') -> None: ...

    def getSceneGraph(self) -> tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.SceneGraph: ...

    def getJoint(self) -> tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.Joint: ...

    def getPrefix(self) -> str: ...

class AddTrajectoryLinkCommand(Command):
    def __init__(self, link_name: str, parent_link_name: str, trajectory: tesseract_robotics.tesseract_common._tesseract_common.JointTrajectory, replace_allowed: bool = False, method: AddTrajectoryLinkCommand.Method = AddTrajectoryLinkCommand.Method.PER_STATE_OBJECTS) -> None: ...

    class Method(enum.Enum):
        PER_STATE_OBJECTS = 0

        PER_STATE_CONVEX_HULL = 1

        GLOBAL_PER_LINK_CONVEX_HULL = 2

        GLOBAL_CONVEX_HULL = 3

    def getLinkName(self) -> str: ...

    def getParentLinkName(self) -> str: ...

    def getTrajectory(self) -> tesseract_robotics.tesseract_common._tesseract_common.JointTrajectory: ...

    def replaceAllowed(self) -> bool: ...

    def getMethod(self) -> AddTrajectoryLinkCommand.Method: ...

    def __eq__(self, arg: AddTrajectoryLinkCommand, /) -> bool: ...

    def __ne__(self, arg: AddTrajectoryLinkCommand, /) -> bool: ...

    __hash__: None = None

class AddKinematicsInformationCommand(Command):
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, kinematics_information: tesseract_robotics.tesseract_srdf._tesseract_srdf.KinematicsInformation) -> None: ...

    def getKinematicsInformation(self) -> tesseract_robotics.tesseract_srdf._tesseract_srdf.KinematicsInformation: ...

class AddContactManagersPluginInfoCommand(Command):
    def __init__(self, contact_managers_plugin_info: tesseract_robotics.tesseract_common._tesseract_common.ContactManagersPluginInfo) -> None: ...

    def getContactManagersPluginInfo(self) -> tesseract_robotics.tesseract_common._tesseract_common.ContactManagersPluginInfo: ...

    def __eq__(self, arg: AddContactManagersPluginInfoCommand, /) -> bool: ...

    def __ne__(self, arg: AddContactManagersPluginInfoCommand, /) -> bool: ...

    __hash__: None = None

class ModifyAllowedCollisionsType(enum.Enum):
    ADD = 0

    REMOVE = 1

    REPLACE = 2

class ModifyAllowedCollisionsCommand(Command):
    def __init__(self, acm: tesseract_robotics.tesseract_common._tesseract_common.AllowedCollisionMatrix, type: ModifyAllowedCollisionsType) -> None: ...

    def getModifyType(self) -> ModifyAllowedCollisionsType: ...

    def getAllowedCollisionMatrix(self) -> tesseract_robotics.tesseract_common._tesseract_common.AllowedCollisionMatrix: ...

class RemoveAllowedCollisionLinkCommand(Command):
    def __init__(self, link_name: str) -> None: ...

    def getLinkName(self) -> str: ...

class ChangeJointPositionLimitsCommand(Command):
    @overload
    def __init__(self, joint_name: str, lower: float, upper: float) -> None: ...

    @overload
    def __init__(self, limits: Mapping[str, tuple[float, float]]) -> None: ...

    def getLimits(self) -> dict[str, tuple[float, float]]: ...

class ChangeJointVelocityLimitsCommand(Command):
    @overload
    def __init__(self, joint_name: str, limit: float) -> None: ...

    @overload
    def __init__(self, limits: Mapping[str, float]) -> None: ...

    def getLimits(self) -> dict[str, float]: ...

class ChangeJointAccelerationLimitsCommand(Command):
    @overload
    def __init__(self, joint_name: str, limit: float) -> None: ...

    @overload
    def __init__(self, limits: Mapping[str, float]) -> None: ...

    def getLimits(self) -> dict[str, float]: ...

class ChangeCollisionMarginsCommand(Command):
    @overload
    def __init__(self, default_margin: float) -> None: ...

    @overload
    def __init__(self, pair_margin_data: tesseract_robotics.tesseract_common._tesseract_common.CollisionMarginPairData, override_type: tesseract_robotics.tesseract_common._tesseract_common.CollisionMarginPairOverrideType = tesseract_robotics.tesseract_common._tesseract_common.CollisionMarginPairOverrideType.REPLACE) -> None: ...

    def getDefaultCollisionMargin(self) -> float | None: ...

    def getCollisionMarginPairData(self) -> tesseract_robotics.tesseract_common._tesseract_common.CollisionMarginPairData: ...

    def getCollisionMarginPairOverrideType(self) -> tesseract_robotics.tesseract_common._tesseract_common.CollisionMarginPairOverrideType: ...

class ChangeLinkCollisionEnabledCommand(Command):
    def __init__(self, link_name: str, enabled: bool) -> None: ...

    def getLinkName(self) -> str: ...

    def getEnabled(self) -> bool: ...

class ChangeLinkVisibilityCommand(Command):
    def __init__(self, link_name: str, visible: bool) -> None: ...

    def getLinkName(self) -> str: ...

    def getEnabled(self) -> bool: ...

class ChangeJointOriginCommand(Command):
    def __init__(self, joint_name: str, origin: tesseract_robotics.tesseract_common._tesseract_common.Isometry3d) -> None: ...

    def getJointName(self) -> str: ...

    def getOrigin(self) -> tesseract_robotics.tesseract_common._tesseract_common.Isometry3d: ...

class ChangeLinkOriginCommand(Command):
    def __init__(self, link_name: str, origin: tesseract_robotics.tesseract_common._tesseract_common.Isometry3d) -> None: ...

    def getLinkName(self) -> str: ...

    def getOrigin(self) -> tesseract_robotics.tesseract_common._tesseract_common.Isometry3d: ...

class MoveJointCommand(Command):
    def __init__(self, joint_name: str, parent_link: str) -> None: ...

    def getJointName(self) -> str: ...

    def getParentLink(self) -> str: ...

class MoveLinkCommand(Command):
    def __init__(self, joint: tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.Joint) -> None: ...

    def getJoint(self) -> tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.Joint: ...

class ReplaceJointCommand(Command):
    def __init__(self, joint: tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.Joint) -> None: ...

    def getJoint(self) -> tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.Joint: ...

class SetActiveDiscreteContactManagerCommand(Command):
    def __init__(self, active_contact_manager: str) -> None: ...

    def getName(self) -> str: ...

    def __eq__(self, arg: SetActiveDiscreteContactManagerCommand, /) -> bool: ...

    def __ne__(self, arg: SetActiveDiscreteContactManagerCommand, /) -> bool: ...

    __hash__: None = None

class SetActiveContinuousContactManagerCommand(Command):
    def __init__(self, active_contact_manager: str) -> None: ...

    def getName(self) -> str: ...

    def __eq__(self, arg: SetActiveContinuousContactManagerCommand, /) -> bool: ...

    def __ne__(self, arg: SetActiveContinuousContactManagerCommand, /) -> bool: ...

    __hash__: None = None

class EnvironmentContactAllowedValidator(tesseract_robotics.tesseract_common._tesseract_common.ContactAllowedValidator):
    def __init__(self, scene_graph: tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.SceneGraph) -> None: ...

class Environment:
    def __init__(self) -> None: ...

    @overload
    def init(self, scene_graph: tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.SceneGraph) -> bool: ...

    @overload
    def init(self, scene_graph: tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.SceneGraph, srdf: tesseract_robotics.tesseract_srdf._tesseract_srdf.SRDFModel) -> bool: ...

    @overload
    def init(self, urdf_string: str, locator: tesseract_robotics.tesseract_common._tesseract_common.ResourceLocator) -> bool: ...

    @overload
    def init(self, urdf_path: os.PathLike, locator: tesseract_robotics.tesseract_common._tesseract_common.ResourceLocator) -> bool: ...

    @overload
    def init(self, urdf_string: str, srdf_string: str, locator: tesseract_robotics.tesseract_common._tesseract_common.ResourceLocator) -> bool: ...

    @overload
    def init(self, urdf_path: os.PathLike, srdf_path: os.PathLike, locator: tesseract_robotics.tesseract_common._tesseract_common.ResourceLocator) -> bool: ...

    @overload
    def init(self, commands: Sequence[Command]) -> bool: ...

    def isInitialized(self) -> bool: ...

    def reset(self) -> bool: ...

    def clear(self) -> None: ...

    def getRevision(self) -> int: ...

    def getInitRevision(self) -> int: ...

    def getTimestamp(self) -> datetime.datetime:
        """
        Last update time (any change to the environment), as a naive local `datetime.datetime`.
        """

    def getCurrentStateTimestamp(self) -> datetime.datetime:
        """
        Last update time of the current state, as a naive local `datetime.datetime`.
        """

    def getName(self) -> str: ...

    def setName(self, name: str) -> None: ...

    def getSceneGraph(self) -> tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.SceneGraph: ...

    @overload
    def getState(self) -> tesseract_robotics.tesseract_state_solver._tesseract_state_solver.SceneState: ...

    @overload
    def getState(self, joints: Mapping[str, float], floating_joints: Mapping[str, tesseract_robotics.tesseract_common._tesseract_common.Isometry3d] = {}) -> tesseract_robotics.tesseract_state_solver._tesseract_state_solver.SceneState: ...

    @overload
    def getState(self, joint_names: Sequence[str], joint_values: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)], floating_joints: Mapping[str, tesseract_robotics.tesseract_common._tesseract_common.Isometry3d] = {}) -> tesseract_robotics.tesseract_state_solver._tesseract_state_solver.SceneState: ...

    @overload
    def getState(self, floating_joints: Mapping[str, tesseract_robotics.tesseract_common._tesseract_common.Isometry3d]) -> tesseract_robotics.tesseract_state_solver._tesseract_state_solver.SceneState: ...

    def getStateByMap(self, joints: Mapping[str, float], floating_joints: Mapping[str, tesseract_robotics.tesseract_common._tesseract_common.Isometry3d] = {}) -> tesseract_robotics.tesseract_state_solver._tesseract_state_solver.SceneState: ...

    def getStateByNamesAndValues(self, joint_names: Sequence[str], joint_values: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)], floating_joints: Mapping[str, tesseract_robotics.tesseract_common._tesseract_common.Isometry3d] = {}) -> tesseract_robotics.tesseract_state_solver._tesseract_state_solver.SceneState: ...

    @overload
    def setState(self, joints: Mapping[str, float], floating_joints: Mapping[str, tesseract_robotics.tesseract_common._tesseract_common.Isometry3d] = {}) -> None: ...

    @overload
    def setState(self, joint_names: Sequence[str], joint_values: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)], floating_joints: Mapping[str, tesseract_robotics.tesseract_common._tesseract_common.Isometry3d] = {}) -> None: ...

    @overload
    def setState(self, floating_joints: Mapping[str, tesseract_robotics.tesseract_common._tesseract_common.Isometry3d]) -> None: ...

    def setStateByNamesAndValues(self, joint_names: Sequence[str], joint_values: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)], floating_joints: Mapping[str, tesseract_robotics.tesseract_common._tesseract_common.Isometry3d] = {}) -> None: ...

    def addEventCallback(self, hash: int, fn: EventCallbackFn) -> None: ...

    def removeEventCallback(self, hash: int) -> None: ...

    def clearEventCallbacks(self) -> None: ...

    @overload
    def applyCommand(self, command: RemoveJointCommand) -> bool: ...

    @overload
    def applyCommand(self, command: AddLinkCommand) -> bool: ...

    @overload
    def applyCommand(self, command: RemoveLinkCommand) -> bool: ...

    @overload
    def applyCommand(self, command: AddSceneGraphCommand) -> bool: ...

    @overload
    def applyCommand(self, command: AddTrajectoryLinkCommand) -> bool: ...

    @overload
    def applyCommand(self, command: AddKinematicsInformationCommand) -> bool: ...

    @overload
    def applyCommand(self, command: AddContactManagersPluginInfoCommand) -> bool: ...

    @overload
    def applyCommand(self, command: ModifyAllowedCollisionsCommand) -> bool: ...

    @overload
    def applyCommand(self, command: RemoveAllowedCollisionLinkCommand) -> bool: ...

    @overload
    def applyCommand(self, command: ChangeJointPositionLimitsCommand) -> bool: ...

    @overload
    def applyCommand(self, command: ChangeJointVelocityLimitsCommand) -> bool: ...

    @overload
    def applyCommand(self, command: ChangeJointAccelerationLimitsCommand) -> bool: ...

    @overload
    def applyCommand(self, command: ChangeCollisionMarginsCommand) -> bool: ...

    @overload
    def applyCommand(self, command: ChangeLinkCollisionEnabledCommand) -> bool: ...

    @overload
    def applyCommand(self, command: ChangeLinkVisibilityCommand) -> bool: ...

    @overload
    def applyCommand(self, command: ChangeJointOriginCommand) -> bool: ...

    @overload
    def applyCommand(self, command: ChangeLinkOriginCommand) -> bool: ...

    @overload
    def applyCommand(self, command: MoveJointCommand) -> bool: ...

    @overload
    def applyCommand(self, command: MoveLinkCommand) -> bool: ...

    @overload
    def applyCommand(self, command: ReplaceJointCommand) -> bool: ...

    @overload
    def applyCommand(self, command: SetActiveDiscreteContactManagerCommand) -> bool: ...

    @overload
    def applyCommand(self, command: SetActiveContinuousContactManagerCommand) -> bool: ...

    def applyCommands(self, commands: Sequence[Command]) -> bool: ...

    def getCommandHistory(self) -> list[Command]: ...

    def getStateSolver(self) -> tesseract_robotics.tesseract_state_solver._tesseract_state_solver.StateSolver: ...

    def getJointNames(self) -> list[str]: ...

    def getActiveJointNames(self) -> list[str]: ...

    def getLinkNames(self) -> list[str]: ...

    @overload
    def getActiveLinkNames(self) -> list[str]: ...

    @overload
    def getActiveLinkNames(self, joint_names: Sequence[str]) -> list[str]: ...

    @overload
    def getStaticLinkNames(self) -> list[str]: ...

    @overload
    def getStaticLinkNames(self, joint_names: Sequence[str]) -> list[str]: ...

    def getRootLinkName(self) -> str: ...

    @overload
    def getCurrentJointValues(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    @overload
    def getCurrentJointValues(self, joint_names: Sequence[str]) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    def getCurrentJointValuesByNames(self, joint_names: Sequence[str]) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    def getLinkTransform(self, link_name: str) -> tesseract_robotics.tesseract_common._tesseract_common.Isometry3d: ...

    def getRelativeLinkTransform(self, from_link_name: str, to_link_name: str) -> tesseract_robotics.tesseract_common._tesseract_common.Isometry3d: ...

    @overload
    def getLinkTransforms(self) -> list[tesseract_robotics.tesseract_common._tesseract_common.Isometry3d]: ...

    @overload
    def getLinkTransforms(self, joint_names: Sequence[str], joint_values: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)]) -> dict[str, tesseract_robotics.tesseract_common._tesseract_common.Isometry3d]: ...

    @overload
    def getLinkTransforms(self, joint_names: Sequence[str], joint_values: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)], floating_joints: Mapping[str, tesseract_robotics.tesseract_common._tesseract_common.Isometry3d]) -> dict[str, tesseract_robotics.tesseract_common._tesseract_common.Isometry3d]: ...

    @overload
    def getCurrentFloatingJointValues(self) -> dict[str, tesseract_robotics.tesseract_common._tesseract_common.Isometry3d]: ...

    @overload
    def getCurrentFloatingJointValues(self, joint_names: Sequence[str]) -> dict[str, tesseract_robotics.tesseract_common._tesseract_common.Isometry3d]: ...

    def getJointLimits(self, joint_name: str) -> tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.JointLimits: ...

    def getLinkCollisionEnabled(self, name: str) -> bool: ...

    def getLinkVisibility(self, name: str) -> bool: ...

    def getContactManagersPluginInfo(self) -> tesseract_robotics.tesseract_common._tesseract_common.ContactManagersPluginInfo: ...

    def getLink(self, name: str) -> tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.Link: ...

    def getJoint(self, name: str) -> tesseract_robotics.tesseract_scene_graph._tesseract_scene_graph.Joint: ...

    def getGroupNames(self) -> set[str]: ...

    def getGroupJointNames(self, group_name: str) -> list[str]: ...

    @overload
    def getJointGroup(self, group_name: str) -> tesseract_robotics.tesseract_kinematics._tesseract_kinematics.JointGroup: ...

    @overload
    def getJointGroup(self, name: str, joint_names: Sequence[str]) -> tesseract_robotics.tesseract_kinematics._tesseract_kinematics.JointGroup: ...

    def getKinematicGroup(self, group_name: str, ik_solver_name: str = '') -> tesseract_robotics.tesseract_kinematics._tesseract_kinematics.KinematicGroup: ...

    def findTCPOffset(self, manip_info: tesseract_robotics.tesseract_common._tesseract_common.ManipulatorInfo) -> tesseract_robotics.tesseract_common._tesseract_common.Isometry3d: ...

    def addFindTCPOffsetCallback(self, fn: Callable[[tesseract_robotics.tesseract_common._tesseract_common.ManipulatorInfo], tesseract_robotics.tesseract_common._tesseract_common.Isometry3d]) -> None:
        """
        Register `fn(manip_info) -> Isometry3d` as a source of TCP offsets for `findTCPOffset`.

        `findTCPOffset` asks the callbacks, in registration order, only for a `tcp_offset` name that is neither an `Isometry3d`, a link, nor a group TCP of `manip_info.manipulator`. `clone()` copies the callbacks, and the environment keeps `fn` alive.

        A callback that raises, or returns anything but an `Isometry3d` (`None` included), counts as "not located": `findTCPOffset` tries the next one and raises `RuntimeError` ("Could not find tcp by name ...") when none returns a transform. The callback's own exception is not reported (upstream catches it with `catch (...)`).

        `fn` may run on any thread, under this environment's lock: it must not call into this environment, and must not keep it alive itself (a closure over it, or an attribute holding it): the environment keeps `fn` alive from C++, so the garbage collector cannot see that cycle.

        Args:
            fn: Callable taking the `ManipulatorInfo` and returning the TCP offset.
        """

    @overload
    def getDiscreteContactManager(self) -> tesseract_robotics.tesseract_collision._tesseract_collision.DiscreteContactManager: ...

    @overload
    def getDiscreteContactManager(self, name: str) -> tesseract_robotics.tesseract_collision._tesseract_collision.DiscreteContactManager: ...

    @overload
    def getContinuousContactManager(self) -> tesseract_robotics.tesseract_collision._tesseract_collision.ContinuousContactManager: ...

    @overload
    def getContinuousContactManager(self, name: str) -> tesseract_robotics.tesseract_collision._tesseract_collision.ContinuousContactManager: ...

    def setActiveDiscreteContactManager(self, name: str) -> bool: ...

    def setActiveContinuousContactManager(self, name: str) -> bool: ...

    def clearCachedDiscreteContactManager(self) -> None: ...

    def clearCachedContinuousContactManager(self) -> None: ...

    def getAllowedCollisionMatrix(self) -> tesseract_robotics.tesseract_common._tesseract_common.AllowedCollisionMatrix: ...

    def getCollisionMarginData(self) -> tesseract_robotics.tesseract_common._tesseract_common.CollisionMarginData: ...

    def setResourceLocator(self, locator: tesseract_robotics.tesseract_common._tesseract_common.ResourceLocator) -> None: ...

    def getResourceLocator(self) -> tesseract_robotics.tesseract_common._tesseract_common.ResourceLocator: ...

    def getKinematicsInformation(self) -> tesseract_robotics.tesseract_srdf._tesseract_srdf.KinematicsInformation: ...

    def clone(self) -> Environment: ...
