"""tesseract_common Python bindings (nanobind)"""

from collections.abc import Sequence
import enum
from typing import Annotated, TypeAlias, overload

import numpy
from numpy.typing import NDArray


EIGEN_DEFAULT_PREC: float = 1e-12

class Isometry3d:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, other: Isometry3d) -> None: ...

    @overload
    def __init__(self, matrix: Annotated[NDArray[numpy.float64], dict(shape=(4, 4), order='F')]) -> None: ...

    @overload
    def __init__(self, rotation_quaternion: Quaterniond) -> None: ...

    @overload
    def __init__(self, rotation_angle_axis: AngleAxisd) -> None: ...

    @overload
    def __init__(self, translation: Translation3d) -> None: ...

    @overload
    def __init__(self, translation: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], rotation: Quaterniond) -> None: ...

    @overload
    def __init__(self, translation: Translation3d, rotation: Quaterniond) -> None: ...

    @staticmethod
    def Identity() -> Isometry3d: ...

    def setIdentity(self) -> None: ...

    @property
    def matrix(self) -> Annotated[NDArray[numpy.float64], dict(shape=(4, 4), order='F')]: ...

    @property
    def translation(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @property
    def rotation(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3, 3), order='F')]: ...

    @property
    def linear(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3, 3), order='F')]: ...

    def inverse(self) -> Isometry3d: ...

    @overload
    def __mul__(self, arg: Isometry3d, /) -> Isometry3d: ...

    @overload
    def __mul__(self, arg: Translation3d, /) -> Isometry3d: ...

    @overload
    def __mul__(self, arg: Quaterniond, /) -> Isometry3d: ...

    @overload
    def __mul__(self, arg: AngleAxisd, /) -> Isometry3d: ...

    @overload
    def __mul__(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], /) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def translate(self, vec: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]) -> Isometry3d: ...

    def pretranslate(self, vec: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]) -> Isometry3d: ...

    @overload
    def rotate(self, rotation: Quaterniond) -> Isometry3d: ...

    @overload
    def rotate(self, rotation: AngleAxisd) -> Isometry3d: ...

    @overload
    def rotate(self, rotation: Annotated[NDArray[numpy.float64], dict(shape=(3, 3), order='F')]) -> Isometry3d: ...

    @overload
    def prerotate(self, rotation: Quaterniond) -> Isometry3d: ...

    @overload
    def prerotate(self, rotation: AngleAxisd) -> Isometry3d: ...

    @overload
    def prerotate(self, rotation: Annotated[NDArray[numpy.float64], dict(shape=(3, 3), order='F')]) -> Isometry3d: ...

    def isApprox(self, other: Isometry3d, prec: float = 1e-12) -> bool: ...

    def __repr__(self) -> str: ...

class Translation3d:
    @overload
    def __init__(self, arg0: float, arg1: float, arg2: float, /) -> None: ...

    @overload
    def __init__(self, vector: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]) -> None: ...

    @property
    def x(self) -> float: ...

    @property
    def y(self) -> float: ...

    @property
    def z(self) -> float: ...

    def translation(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def inverse(self) -> Translation3d: ...

    @overload
    def __mul__(self, arg: Isometry3d, /) -> Isometry3d: ...

    @overload
    def __mul__(self, arg: Translation3d, /) -> Translation3d: ...

    @overload
    def __mul__(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], /) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def isApprox(self, other: Translation3d, prec: float = 1e-12) -> bool: ...

    def __repr__(self) -> str: ...

class Quaterniond:
    @overload
    def __init__(self, arg0: float, arg1: float, arg2: float, arg3: float, /) -> None: ...

    @overload
    def __init__(self, rotation_matrix: Annotated[NDArray[numpy.float64], dict(shape=(3, 3), order='F')]) -> None: ...

    @overload
    def __init__(self, angle_axis: AngleAxisd) -> None: ...

    @overload
    def __init__(self, coeffs: Annotated[NDArray[numpy.float64], dict(shape=(4), order='C')]) -> None: ...

    @staticmethod
    def Identity() -> Quaterniond: ...

    @staticmethod
    def FromTwoVectors(a: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], b: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]) -> Quaterniond: ...

    @staticmethod
    def from_xyzw(qx: float, qy: float, qz: float, qw: float) -> Quaterniond: ...

    @overload
    @staticmethod
    def from_rpy(roll: float, pitch: float, yaw: float) -> Quaterniond: ...

    @overload
    @staticmethod
    def from_rpy(rpy: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]) -> Quaterniond: ...

    @property
    def w(self) -> float: ...

    @property
    def x(self) -> float: ...

    @property
    def y(self) -> float: ...

    @property
    def z(self) -> float: ...

    def coeffs(self) -> Annotated[NDArray[numpy.float64], dict(shape=(4), order='C')]: ...

    def vec(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def toRotationMatrix(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3, 3), order='F')]: ...

    def slerp(self, t: float, other: Quaterniond) -> Quaterniond: ...

    @overload
    def __mul__(self, arg: Quaterniond, /) -> Quaterniond: ...

    @overload
    def __mul__(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], /) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def conjugate(self) -> Quaterniond: ...

    def inverse(self) -> Quaterniond: ...

    def dot(self, arg: Quaterniond, /) -> float: ...

    def angularDistance(self, arg: Quaterniond, /) -> float: ...

    def norm(self) -> float: ...

    def squaredNorm(self) -> float: ...

    def normalize(self) -> None: ...

    def normalized(self) -> Quaterniond: ...

    def setIdentity(self) -> None: ...

    def isApprox(self, other: Quaterniond, prec: float = 1e-12) -> bool: ...

    def to_rpy(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def eulerAngles(self, order: str) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def __repr__(self) -> str: ...

class AngleAxisd:
    @overload
    def __init__(self, arg0: float, arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], /) -> None: ...

    @overload
    def __init__(self, quaternion: Quaterniond) -> None: ...

    @overload
    def __init__(self, rotation_matrix: Annotated[NDArray[numpy.float64], dict(shape=(3, 3), order='F')]) -> None: ...

    @property
    def angle(self) -> float: ...

    @property
    def axis(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def inverse(self) -> AngleAxisd: ...

    def toRotationMatrix(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3, 3), order='F')]: ...

    def isApprox(self, other: AngleAxisd, prec: float = 1e-12) -> bool: ...

    def __repr__(self) -> str: ...

class Hyperplane3d:
    @overload
    def __init__(self, normal: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], offset: float) -> None: ...

    @overload
    def __init__(self, normal: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], point: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]) -> None: ...

    @staticmethod
    def Through(p0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], p1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], p2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]) -> Hyperplane3d: ...

    @property
    def normal(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @property
    def offset(self) -> float: ...

    def coeffs(self) -> Annotated[NDArray[numpy.float64], dict(shape=(4), order='C')]: ...

    def signedDistance(self, point: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]) -> float: ...

    def absDistance(self, point: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]) -> float: ...

    def projection(self, point: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def normalize(self) -> Hyperplane3d: ...

    def transform(self, transform: Isometry3d) -> Hyperplane3d: ...

    def isApprox(self, other: Hyperplane3d, prec: float = 1e-12) -> bool: ...

    def __repr__(self) -> str: ...

class ParametrizedLine3d:
    def __init__(self, origin: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], direction: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]) -> None: ...

    @staticmethod
    def Through(p0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], p1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]) -> ParametrizedLine3d: ...

    @property
    def origin(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @property
    def direction(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def distance(self, point: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]) -> float: ...

    def squaredDistance(self, point: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]) -> float: ...

    def projection(self, point: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def pointAt(self, t: float) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def intersectionParameter(self, plane: Hyperplane3d) -> float: ...

    def intersectionPoint(self, plane: Hyperplane3d) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def transform(self, transform: Isometry3d) -> ParametrizedLine3d: ...

    def isApprox(self, other: ParametrizedLine3d, prec: float = 1e-12) -> bool: ...

    def __repr__(self) -> str: ...

class FilesystemPath:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, path: str) -> None: ...

    def string(self) -> str: ...

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

class Resource:
    def isFile(self) -> bool: ...

    def getUrl(self) -> str: ...

    def getFilePath(self) -> str: ...

    def getResourceContents(self) -> bytes: ...

    def getResourceContentStream(self) -> "std::__1::basic_istream<char, std::__1::char_traits<char>>": ...

class BytesResource(Resource):
    @overload
    def __init__(self, arg0: str, arg1: Sequence[int], /) -> None: ...

    @overload
    def __init__(self, arg0: str, arg1: bytes, /) -> None: ...

class SimpleLocatedResource(Resource):
    @overload
    def __init__(self, url: str, filename: str) -> None: ...

    @overload
    def __init__(self, url: str, filename: str, parent: ResourceLocator) -> None: ...

class ResourceLocator:
    def __init__(self) -> None: ...

    def locateResource(self, arg: str, /) -> Resource: ...

class GeneralResourceLocator(ResourceLocator):
    def __init__(self) -> None: ...

class ManipulatorInfo:
    def __init__(self) -> None: ...

    @property
    def manipulator(self) -> str: ...

    @manipulator.setter
    def manipulator(self, arg: str, /) -> None: ...

    @property
    def manipulator_ik_solver(self) -> str: ...

    @manipulator_ik_solver.setter
    def manipulator_ik_solver(self, arg: str, /) -> None: ...

    @property
    def working_frame(self) -> str: ...

    @working_frame.setter
    def working_frame(self, arg: str, /) -> None: ...

    @property
    def tcp_frame(self) -> str: ...

    @tcp_frame.setter
    def tcp_frame(self, arg: str, /) -> None: ...

    @property
    def tcp_offset(self) -> object: ...

    @tcp_offset.setter
    def tcp_offset(self, arg: object, /) -> None: ...

    def __repr__(self) -> str: ...

class JointState:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg0: Sequence[str], arg1: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], /) -> None: ...

    @property
    def joint_names(self) -> list[str]: ...

    @joint_names.setter
    def joint_names(self, arg: Sequence[str], /) -> None: ...

    @property
    def position(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    @position.setter
    def position(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], /) -> None: ...

    @property
    def velocity(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    @velocity.setter
    def velocity(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], /) -> None: ...

    @property
    def acceleration(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    @acceleration.setter
    def acceleration(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], /) -> None: ...

    @property
    def effort(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    @effort.setter
    def effort(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], /) -> None: ...

    @property
    def time(self) -> float: ...

    @time.setter
    def time(self, arg: float, /) -> None: ...

class AllowedCollisionMatrix:
    def __init__(self) -> None: ...

    def addAllowedCollision(self, arg0: str, arg1: str, arg2: str, /) -> None: ...

    def removeAllowedCollision(self, arg0: str, arg1: str, /) -> None: ...

    def isCollisionAllowed(self, arg0: str, arg1: str, /) -> bool: ...

    def clearAllowedCollisions(self) -> None: ...

    def getAllAllowedCollisions(self) -> dict[tuple[str, str], str]: ...

    def insertAllowedCollisionMatrix(self, arg: AllowedCollisionMatrix, /) -> None: ...

class CollisionMarginPairOverrideType(enum.Enum):
    NONE = 0

    REPLACE = 1

    MODIFY = 2

CollisionMarginOverrideType: TypeAlias = CollisionMarginPairOverrideType

class CollisionMarginPairData:
    def __init__(self) -> None: ...

    def setCollisionMargin(self, arg0: str, arg1: str, arg2: float, /) -> None: ...

    def getCollisionMargin(self, arg0: str, arg1: str, /) -> float | None: ...

    def getCollisionMargins(self) -> dict[tuple[str, str], float]: ...

    def empty(self) -> bool: ...

    def clear(self) -> None: ...

class CollisionMarginData:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg: float, /) -> None: ...

    def getDefaultCollisionMargin(self) -> float: ...

    def setDefaultCollisionMargin(self, arg: float, /) -> None: ...

    def getCollisionMargin(self, arg0: str, arg1: str, /) -> float: ...

    def setCollisionMargin(self, arg0: str, arg1: str, arg2: float, /) -> None: ...

    def getCollisionMarginPairData(self) -> CollisionMarginPairData: ...

    def getMaxCollisionMargin(self) -> float: ...

    def getPairCollisionMargin(self, arg0: str, arg1: str, /) -> float: ...

    def setPairCollisionMargin(self, arg0: str, arg1: str, arg2: float, /) -> None: ...

class KinematicLimits:
    def __init__(self) -> None: ...

    @property
    def joint_limits(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='F')]: ...

    @joint_limits.setter
    def joint_limits(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='F')], /) -> None: ...

    @property
    def velocity_limits(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='F')]: ...

    @velocity_limits.setter
    def velocity_limits(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='F')], /) -> None: ...

    @property
    def acceleration_limits(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='F')]: ...

    @acceleration_limits.setter
    def acceleration_limits(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='F')], /) -> None: ...

class PluginInfo:
    def __init__(self) -> None: ...

    @property
    def class_name(self) -> str: ...

    @class_name.setter
    def class_name(self, arg: str, /) -> None: ...

    @property
    def config(self) -> "YAML::Node": ...

    @config.setter
    def config(self, arg: "YAML::Node", /) -> None: ...

class LogLevel(enum.Enum):
    CONSOLE_BRIDGE_LOG_DEBUG = 0

    CONSOLE_BRIDGE_LOG_INFO = 1

    CONSOLE_BRIDGE_LOG_WARN = 2

    CONSOLE_BRIDGE_LOG_ERROR = 3

    CONSOLE_BRIDGE_LOG_NONE = 4

CONSOLE_BRIDGE_LOG_DEBUG: LogLevel = LogLevel.CONSOLE_BRIDGE_LOG_DEBUG

CONSOLE_BRIDGE_LOG_INFO: LogLevel = LogLevel.CONSOLE_BRIDGE_LOG_INFO

CONSOLE_BRIDGE_LOG_WARN: LogLevel = LogLevel.CONSOLE_BRIDGE_LOG_WARN

CONSOLE_BRIDGE_LOG_ERROR: LogLevel = LogLevel.CONSOLE_BRIDGE_LOG_ERROR

CONSOLE_BRIDGE_LOG_NONE: LogLevel = LogLevel.CONSOLE_BRIDGE_LOG_NONE

class OutputHandler:
    def __init__(self) -> None: ...

    def log(self, arg0: str, arg1: LogLevel, arg2: str, arg3: int, /) -> None: ...

def setLogLevel(level: LogLevel) -> None: ...

def getLogLevel() -> LogLevel: ...

def log(filename: str, line: int, level: LogLevel, msg: str) -> None: ...

def useOutputHandler(handler: OutputHandler) -> None: ...

def restorePreviousOutputHandler() -> None: ...

class VectorVector3d:
    def __init__(self) -> None: ...

    def __len__(self) -> int: ...

    def __getitem__(self, arg: int, /) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def __setitem__(self, arg0: int, arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], /) -> None: ...

    def append(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], /) -> None: ...

    def clear(self) -> None: ...

class VectorIsometry3d:
    def __init__(self) -> None: ...

    def __len__(self) -> int: ...

    def __getitem__(self, arg: int, /) -> Isometry3d: ...

    def append(self, arg: Isometry3d, /) -> None: ...

    def clear(self) -> None: ...
