"""tesseract_common Python bindings (nanobind)"""

from collections.abc import Callable, Mapping, Sequence
import datetime
import enum
from typing import Annotated, TypeAlias, overload

import numpy
from numpy.typing import NDArray


class LinkId:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, name: str) -> None: ...

    def name(self) -> str: ...

    def value(self) -> int: ...

    def isValid(self) -> bool: ...

    @overload
    def __eq__(self, arg: LinkId, /) -> bool: ...

    @overload
    def __eq__(self, arg: str, /) -> bool: ...

    @overload
    def __ne__(self, arg: LinkId, /) -> bool: ...

    @overload
    def __ne__(self, arg: str, /) -> bool: ...

    def __lt__(self, arg: LinkId, /) -> bool: ...

    def __hash__(self) -> int: ...

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

    def __getstate__(self) -> str: ...

    def __setstate__(self, arg: str, /) -> None: ...

class JointId:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, name: str) -> None: ...

    def name(self) -> str: ...

    def value(self) -> int: ...

    def isValid(self) -> bool: ...

    @overload
    def __eq__(self, arg: JointId, /) -> bool: ...

    @overload
    def __eq__(self, arg: str, /) -> bool: ...

    @overload
    def __ne__(self, arg: JointId, /) -> bool: ...

    @overload
    def __ne__(self, arg: str, /) -> bool: ...

    def __lt__(self, arg: JointId, /) -> bool: ...

    def __hash__(self) -> int: ...

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

    def __getstate__(self) -> str: ...

    def __setstate__(self, arg: str, /) -> None: ...

class LinkIdPair:
    @overload
    def __init__(self, link_id1: LinkId, link_id2: LinkId) -> None: ...

    @overload
    def __init__(self, pair: tuple[LinkId, LinkId]) -> None: ...

    def first(self) -> LinkId: ...

    def second(self) -> LinkId: ...

    def orderedNameView(self) -> tuple[str, str]: ...

    def __eq__(self, arg: LinkIdPair) -> bool: ...

    def __ne__(self, arg: LinkIdPair) -> bool: ...

    def __hash__(self) -> int: ...

    def __repr__(self) -> str: ...

EIGEN_DEFAULT_PREC: float = 1e-12

class Isometry3d:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, other: Isometry3d) -> None: ...

    @overload
    def __init__(self, matrix: Annotated[NDArray[numpy.float64], dict(shape=(4, 4), order='F')]) -> None: ...

    @overload
    def __init__(self, rotation_quaternion: Quaterniond) -> None: ...

    @overload
    def __init__(self, rotation_angle_axis: AngleAxisd) -> None: ...

    @overload
    def __init__(self, translation: Translation3d) -> None: ...

    @overload
    def __init__(self, translation: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], rotation: Quaterniond) -> None: ...

    @overload
    def __init__(self, translation: Translation3d, rotation: Quaterniond) -> None: ...

    @staticmethod
    def Identity() -> Isometry3d: ...

    def setIdentity(self) -> None: ...

    @property
    def matrix(self) -> Annotated[NDArray[numpy.float64], dict(shape=(4, 4), order='F')]: ...

    @property
    def translation(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @property
    def rotation(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3, 3), order='F')]: ...

    @property
    def linear(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3, 3), order='F')]: ...

    def inverse(self) -> Isometry3d: ...

    @overload
    def __mul__(self, arg: Isometry3d, /) -> Isometry3d: ...

    @overload
    def __mul__(self, arg: Translation3d, /) -> Isometry3d: ...

    @overload
    def __mul__(self, arg: Quaterniond, /) -> Isometry3d: ...

    @overload
    def __mul__(self, arg: AngleAxisd, /) -> Isometry3d: ...

    @overload
    def __mul__(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], /) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def translate(self, vec: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]) -> Isometry3d: ...

    def pretranslate(self, vec: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]) -> Isometry3d: ...

    @overload
    def rotate(self, rotation: Quaterniond) -> Isometry3d: ...

    @overload
    def rotate(self, rotation: AngleAxisd) -> Isometry3d: ...

    @overload
    def rotate(self, rotation: Annotated[NDArray[numpy.float64], dict(shape=(3, 3), order='F')]) -> Isometry3d: ...

    @overload
    def prerotate(self, rotation: Quaterniond) -> Isometry3d: ...

    @overload
    def prerotate(self, rotation: AngleAxisd) -> Isometry3d: ...

    @overload
    def prerotate(self, rotation: Annotated[NDArray[numpy.float64], dict(shape=(3, 3), order='F')]) -> Isometry3d: ...

    def isApprox(self, other: Isometry3d, prec: float = 1e-12) -> bool: ...

    def __repr__(self) -> str: ...

class Translation3d:
    @overload
    def __init__(self, arg0: float, arg1: float, arg2: float, /) -> None: ...

    @overload
    def __init__(self, vector: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]) -> None: ...

    @property
    def x(self) -> float: ...

    @property
    def y(self) -> float: ...

    @property
    def z(self) -> float: ...

    def translation(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def inverse(self) -> Translation3d: ...

    @overload
    def __mul__(self, arg: Isometry3d, /) -> Isometry3d: ...

    @overload
    def __mul__(self, arg: Translation3d, /) -> Translation3d: ...

    @overload
    def __mul__(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], /) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def isApprox(self, other: Translation3d, prec: float = 1e-12) -> bool: ...

    def __repr__(self) -> str: ...

class Quaterniond:
    @overload
    def __init__(self, arg0: float, arg1: float, arg2: float, arg3: float, /) -> None: ...

    @overload
    def __init__(self, rotation_matrix: Annotated[NDArray[numpy.float64], dict(shape=(3, 3), order='F')]) -> None: ...

    @overload
    def __init__(self, angle_axis: AngleAxisd) -> None: ...

    @overload
    def __init__(self, coeffs: Annotated[NDArray[numpy.float64], dict(shape=(4), order='C')]) -> None: ...

    @staticmethod
    def Identity() -> Quaterniond: ...

    @staticmethod
    def FromTwoVectors(a: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], b: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]) -> Quaterniond: ...

    @staticmethod
    def from_xyzw(qx: float, qy: float, qz: float, qw: float) -> Quaterniond: ...

    @overload
    @staticmethod
    def from_rpy(roll: float, pitch: float, yaw: float) -> Quaterniond: ...

    @overload
    @staticmethod
    def from_rpy(rpy: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]) -> Quaterniond: ...

    @property
    def w(self) -> float: ...

    @property
    def x(self) -> float: ...

    @property
    def y(self) -> float: ...

    @property
    def z(self) -> float: ...

    def coeffs(self) -> Annotated[NDArray[numpy.float64], dict(shape=(4), order='C')]: ...

    def vec(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def toRotationMatrix(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3, 3), order='F')]: ...

    def slerp(self, t: float, other: Quaterniond) -> Quaterniond: ...

    @overload
    def __mul__(self, arg: Quaterniond, /) -> Quaterniond: ...

    @overload
    def __mul__(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], /) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def conjugate(self) -> Quaterniond: ...

    def inverse(self) -> Quaterniond: ...

    def dot(self, arg: Quaterniond, /) -> float: ...

    def angularDistance(self, arg: Quaterniond, /) -> float: ...

    def norm(self) -> float: ...

    def squaredNorm(self) -> float: ...

    def normalize(self) -> None: ...

    def normalized(self) -> Quaterniond: ...

    def setIdentity(self) -> None: ...

    def isApprox(self, other: Quaterniond, prec: float = 1e-12) -> bool: ...

    def to_rpy(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def eulerAngles(self, order: str) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def __repr__(self) -> str: ...

class AngleAxisd:
    @overload
    def __init__(self, arg0: float, arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], /) -> None: ...

    @overload
    def __init__(self, quaternion: Quaterniond) -> None: ...

    @overload
    def __init__(self, rotation_matrix: Annotated[NDArray[numpy.float64], dict(shape=(3, 3), order='F')]) -> None: ...

    @property
    def angle(self) -> float: ...

    @property
    def axis(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def inverse(self) -> AngleAxisd: ...

    def toRotationMatrix(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3, 3), order='F')]: ...

    def isApprox(self, other: AngleAxisd, prec: float = 1e-12) -> bool: ...

    def __repr__(self) -> str: ...

class Hyperplane3d:
    @overload
    def __init__(self, normal: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], offset: float) -> None: ...

    @overload
    def __init__(self, normal: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], point: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]) -> None: ...

    @staticmethod
    def Through(p0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], p1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], p2: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]) -> Hyperplane3d: ...

    @property
    def normal(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @property
    def offset(self) -> float: ...

    def coeffs(self) -> Annotated[NDArray[numpy.float64], dict(shape=(4), order='C')]: ...

    def signedDistance(self, point: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]) -> float: ...

    def absDistance(self, point: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]) -> float: ...

    def projection(self, point: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def normalize(self) -> Hyperplane3d: ...

    def transform(self, transform: Isometry3d) -> Hyperplane3d: ...

    def isApprox(self, other: Hyperplane3d, prec: float = 1e-12) -> bool: ...

    def __repr__(self) -> str: ...

class ParametrizedLine3d:
    def __init__(self, origin: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], direction: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]) -> None: ...

    @staticmethod
    def Through(p0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], p1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]) -> ParametrizedLine3d: ...

    @property
    def origin(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @property
    def direction(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def distance(self, point: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]) -> float: ...

    def squaredDistance(self, point: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]) -> float: ...

    def projection(self, point: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def pointAt(self, t: float) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def intersectionParameter(self, plane: Hyperplane3d) -> float: ...

    def intersectionPoint(self, plane: Hyperplane3d) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def transform(self, transform: Isometry3d) -> ParametrizedLine3d: ...

    def isApprox(self, other: ParametrizedLine3d, prec: float = 1e-12) -> bool: ...

    def __repr__(self) -> str: ...

class FilesystemPath:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, path: str) -> None: ...

    def string(self) -> str: ...

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

class Resource:
    def isFile(self) -> bool: ...

    def getUrl(self) -> str: ...

    def getFilePath(self) -> str: ...

    def getResourceContents(self) -> bytes: ...

    def getResourceContentStream(self) -> "std::__1::basic_istream<char, std::__1::char_traits<char>>": ...

class BytesResource(Resource):
    @overload
    def __init__(self, arg0: str, arg1: Sequence[int], /) -> None: ...

    @overload
    def __init__(self, arg0: str, arg1: bytes, /) -> None: ...

class SimpleLocatedResource(Resource):
    @overload
    def __init__(self, url: str, filename: str) -> None: ...

    @overload
    def __init__(self, url: str, filename: str, parent: ResourceLocator) -> None: ...

class ResourceLocator:
    def __init__(self) -> None: ...

    def locateResource(self, arg: str, /) -> Resource: ...

class GeneralResourceLocator(ResourceLocator):
    def __init__(self) -> None: ...

class ManipulatorInfo:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, manipulator: str, working_frame: LinkId | str, tcp_frame: LinkId | str) -> None: ...

    @property
    def manipulator(self) -> str: ...

    @manipulator.setter
    def manipulator(self, arg: str, /) -> None: ...

    @property
    def manipulator_ik_solver(self) -> str: ...

    @manipulator_ik_solver.setter
    def manipulator_ik_solver(self, arg: str, /) -> None: ...

    @property
    def working_frame(self) -> LinkId: ...

    @working_frame.setter
    def working_frame(self, arg: LinkId | str, /) -> None: ...

    @property
    def tcp_frame(self) -> LinkId: ...

    @tcp_frame.setter
    def tcp_frame(self, arg: LinkId | str, /) -> None: ...

    @property
    def tcp_offset(self) -> object: ...

    @tcp_offset.setter
    def tcp_offset(self, arg: object, /) -> None: ...

    def __repr__(self) -> str: ...

class JointState:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, joint_ids: Sequence[JointId | str], position: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]) -> None: ...

    @property
    def joint_ids(self) -> list[JointId]: ...

    @joint_ids.setter
    def joint_ids(self, arg: Sequence[JointId | str], /) -> None: ...

    @property
    def position(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    @position.setter
    def position(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], /) -> None: ...

    @property
    def velocity(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    @velocity.setter
    def velocity(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], /) -> None: ...

    @property
    def acceleration(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    @acceleration.setter
    def acceleration(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], /) -> None: ...

    @property
    def effort(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    @effort.setter
    def effort(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], /) -> None: ...

    @property
    def time(self) -> float: ...

    @time.setter
    def time(self, arg: float, /) -> None: ...

class AllowedCollisionMatrix:
    def __init__(self) -> None: ...

    @overload
    def addAllowedCollision(self, link_id1: LinkId | str, link_id2: LinkId | str, reason: str) -> None: ...

    @overload
    def addAllowedCollision(self, pair: LinkIdPair | tuple[str, str], reason: str) -> None: ...

    @overload
    def removeAllowedCollision(self, link_id1: LinkId | str, link_id2: LinkId | str) -> None: ...

    @overload
    def removeAllowedCollision(self, pair: LinkIdPair | tuple[str, str]) -> None: ...

    @overload
    def removeAllowedCollision(self, link_id: LinkId | str) -> None: ...

    def isCollisionAllowed(self, pair: LinkIdPair | tuple[str, str]) -> bool: ...

    def clearAllowedCollisions(self) -> None: ...

    def getAllAllowedCollisions(self) -> dict[LinkIdPair, str]: ...

    def insertAllowedCollisionMatrix(self, arg: AllowedCollisionMatrix, /) -> None: ...

class ContactAllowedValidator:
    def __call__(self, pair: LinkIdPair | tuple[str, str]) -> bool: ...

class ACMContactAllowedValidator(ContactAllowedValidator):
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, acm: AllowedCollisionMatrix) -> None: ...

class CombinedContactAllowedValidatorType(enum.Enum):
    AND = 0

    OR = 1

class CombinedContactAllowedValidator(ContactAllowedValidator):
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, validators: Sequence[ContactAllowedValidator], type: CombinedContactAllowedValidatorType) -> None: ...

class CollisionMarginPairOverrideType(enum.Enum):
    NONE = 0

    REPLACE = 1

    MODIFY = 2

CollisionMarginOverrideType: TypeAlias = CollisionMarginPairOverrideType

class CollisionMarginPairData:
    def __init__(self) -> None: ...

    def setCollisionMargin(self, link_id1: LinkId | str, link_id2: LinkId | str, margin: float) -> None: ...

    def getCollisionMargin(self, pair: LinkIdPair | tuple[str, str]) -> float | None: ...

    def getCollisionMargins(self) -> dict[LinkIdPair, float]: ...

    def empty(self) -> bool: ...

    def clear(self) -> None: ...

class CollisionMarginData:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg: float, /) -> None: ...

    def getDefaultCollisionMargin(self) -> float: ...

    def setDefaultCollisionMargin(self, arg: float, /) -> None: ...

    @overload
    def getCollisionMargin(self, link_id1: LinkId | str, link_id2: LinkId | str) -> float: ...

    @overload
    def getCollisionMargin(self, pair: LinkIdPair | tuple[str, str]) -> float: ...

    def setCollisionMargin(self, link_id1: LinkId | str, link_id2: LinkId | str, collision_margin: float) -> None: ...

    def getCollisionMarginPairData(self) -> CollisionMarginPairData: ...

    @overload
    def getMaxCollisionMargin(self) -> float: ...

    @overload
    def getMaxCollisionMargin(self, link_id: LinkId | str) -> float: ...

    def getPairCollisionMargin(self, link_id1: LinkId | str, link_id2: LinkId | str) -> float: ...

    def setPairCollisionMargin(self, link_id1: LinkId | str, link_id2: LinkId | str, collision_margin: float) -> None: ...

class KinematicLimits:
    def __init__(self) -> None: ...

    @property
    def joint_limits(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='F')]: ...

    @joint_limits.setter
    def joint_limits(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='F')], /) -> None: ...

    @property
    def velocity_limits(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='F')]: ...

    @velocity_limits.setter
    def velocity_limits(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='F')], /) -> None: ...

    @property
    def acceleration_limits(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='F')]: ...

    @acceleration_limits.setter
    def acceleration_limits(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='F')], /) -> None: ...

class PluginInfo:
    def __init__(self) -> None: ...

    @property
    def class_name(self) -> str: ...

    @class_name.setter
    def class_name(self, arg: str, /) -> None: ...

    @property
    def config(self) -> str: ...

    @config.setter
    def config(self, arg: str, /) -> None: ...

    def getConfigString(self) -> str: ...

class PluginInfoContainer:
    def __init__(self) -> None: ...

    @property
    def default_plugin(self) -> str: ...

    @default_plugin.setter
    def default_plugin(self, arg: str, /) -> None: ...

    @property
    def plugins(self) -> dict[str, PluginInfo]: ...

    @plugins.setter
    def plugins(self, arg: Mapping[str, PluginInfo], /) -> None: ...

    def clear(self) -> None: ...

class KinematicsPluginInfo:
    def __init__(self) -> None: ...

    @property
    def search_paths(self) -> list[str]: ...

    @search_paths.setter
    def search_paths(self, arg: Sequence[str], /) -> None: ...

    @property
    def search_libraries(self) -> list[str]: ...

    @search_libraries.setter
    def search_libraries(self, arg: Sequence[str], /) -> None: ...

    @property
    def fwd_plugin_infos(self) -> dict[str, PluginInfoContainer]: ...

    @fwd_plugin_infos.setter
    def fwd_plugin_infos(self, arg: Mapping[str, PluginInfoContainer], /) -> None: ...

    @property
    def inv_plugin_infos(self) -> dict[str, PluginInfoContainer]: ...

    @inv_plugin_infos.setter
    def inv_plugin_infos(self, arg: Mapping[str, PluginInfoContainer], /) -> None: ...

    def insert(self, other: KinematicsPluginInfo) -> None: ...

    def clear(self) -> None: ...

    def empty(self) -> bool: ...

class LogLevel(enum.Enum):
    trace = 0

    debug = 1

    info = 2

    warn = 3

    err = 4

    critical = 5

    off = 6

class Logger:
    """A named spdlog logger (tesseract's default is 'tesseract')"""

    def name(self) -> str: ...

    def level(self) -> LogLevel: ...

    def set_level(self, level: LogLevel) -> None: ...

    def should_log(self, level: LogLevel) -> bool: ...

class LogRecord:
    """One tesseract log event, as passed to a record handler"""

    @property
    def timestamp(self) -> datetime.datetime: ...

    @property
    def level(self) -> LogLevel: ...

    @property
    def logger_name(self) -> str: ...

    @property
    def component_name(self) -> str: ...

    @property
    def message(self) -> str: ...

    @property
    def attributes(self) -> dict[str, bool | int | int | float | str]: ...

    @property
    def filename(self) -> str: ...

    @property
    def line(self) -> int: ...

    @property
    def function_name(self) -> str: ...

def getLogger(name: str = 'tesseract') -> Logger:
    """
    Get (or create) a tesseract spdlog logger; set_level() on it controls tesseract's output
    """

def isLogLevelEnabled(level: LogLevel) -> bool:
    """Whether the default tesseract logger emits at this level"""

def addLogRecordHandler(handler: Callable) -> int:
    """
    Register handler(record: LogRecord), called for every emitted record; returns its id
    """

def removeLogRecordHandler(handler_id: int) -> bool:
    """Unregister a handler by id; False if the id is not registered"""

class VectorVector3d:
    def __init__(self) -> None: ...

    def __len__(self) -> int: ...

    def __getitem__(self, arg: int, /) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def __setitem__(self, arg0: int, arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], /) -> None: ...

    def append(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], /) -> None: ...

    def clear(self) -> None: ...

class VectorIsometry3d:
    def __init__(self) -> None: ...

    def __len__(self) -> int: ...

    def __getitem__(self, arg: int, /) -> Isometry3d: ...

    def append(self, arg: Isometry3d, /) -> None: ...

    def clear(self) -> None: ...
