"""tesseract_state_solver Python bindings"""

from collections.abc import Mapping, Sequence
from typing import Annotated, overload

import numpy
from numpy.typing import NDArray

import tesseract_robotics.tesseract_common._tesseract_common


class SceneState:
    def __init__(self) -> None: ...

    @property
    def joints(self) -> dict[tesseract_robotics.tesseract_common._tesseract_common.JointId, float]: ...

    @joints.setter
    def joints(self, arg: Mapping[tesseract_robotics.tesseract_common._tesseract_common.JointId, float], /) -> None: ...

    @property
    def link_transforms(self) -> dict[tesseract_robotics.tesseract_common._tesseract_common.LinkId, tesseract_robotics.tesseract_common._tesseract_common.Isometry3d]: ...

    @link_transforms.setter
    def link_transforms(self, arg: Mapping[tesseract_robotics.tesseract_common._tesseract_common.LinkId, tesseract_robotics.tesseract_common._tesseract_common.Isometry3d], /) -> None: ...

    @property
    def joint_transforms(self) -> dict[tesseract_robotics.tesseract_common._tesseract_common.JointId, tesseract_robotics.tesseract_common._tesseract_common.Isometry3d]: ...

    @joint_transforms.setter
    def joint_transforms(self, arg: Mapping[tesseract_robotics.tesseract_common._tesseract_common.JointId, tesseract_robotics.tesseract_common._tesseract_common.Isometry3d], /) -> None: ...

    def getJointValues(self, joint_ids: Sequence[tesseract_robotics.tesseract_common._tesseract_common.JointId | str]) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

class StateSolver:
    @overload
    def getState(self) -> SceneState: ...

    @overload
    def getState(self, joint_values: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)]) -> SceneState: ...

    @overload
    def getState(self, joint_values: Mapping[tesseract_robotics.tesseract_common._tesseract_common.JointId, float]) -> SceneState: ...

    @overload
    def getState(self, joint_ids: Sequence[tesseract_robotics.tesseract_common._tesseract_common.JointId | str], joint_values: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)]) -> SceneState: ...

    def getRandomState(self) -> SceneState: ...

    def setState(self, joint_values: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)]) -> None: ...

    def setStateByMap(self, joint_values: Mapping[tesseract_robotics.tesseract_common._tesseract_common.JointId, float]) -> None: ...

    def setStateByNamesAndValues(self, joint_ids: Sequence[tesseract_robotics.tesseract_common._tesseract_common.JointId | str], joint_values: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)]) -> None: ...

    def getJacobian(self, joint_values: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)], link_id: tesseract_robotics.tesseract_common._tesseract_common.LinkId | str) -> Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='F')]: ...

    def getJointIds(self) -> list[tesseract_robotics.tesseract_common._tesseract_common.JointId]: ...

    def getFloatingJointIds(self) -> list[tesseract_robotics.tesseract_common._tesseract_common.JointId]: ...

    def getActiveJointIds(self) -> list[tesseract_robotics.tesseract_common._tesseract_common.JointId]: ...

    def getBaseLinkId(self) -> tesseract_robotics.tesseract_common._tesseract_common.LinkId: ...

    def getLinkIds(self) -> list[tesseract_robotics.tesseract_common._tesseract_common.LinkId]: ...

    def getActiveLinkIds(self) -> list[tesseract_robotics.tesseract_common._tesseract_common.LinkId]: ...

    def getStaticLinkIds(self) -> list[tesseract_robotics.tesseract_common._tesseract_common.LinkId]: ...

    def isActiveLinkId(self, link_id: tesseract_robotics.tesseract_common._tesseract_common.LinkId | str) -> bool: ...

    def hasLinkId(self, link_id: tesseract_robotics.tesseract_common._tesseract_common.LinkId | str) -> bool: ...

    def getLinkTransform(self, link_id: tesseract_robotics.tesseract_common._tesseract_common.LinkId | str) -> tesseract_robotics.tesseract_common._tesseract_common.Isometry3d: ...

    def getRelativeLinkTransform(self, from_link_id: tesseract_robotics.tesseract_common._tesseract_common.LinkId | str, to_link_id: tesseract_robotics.tesseract_common._tesseract_common.LinkId | str) -> tesseract_robotics.tesseract_common._tesseract_common.Isometry3d: ...

    def getLimits(self) -> tesseract_robotics.tesseract_common._tesseract_common.KinematicLimits: ...

    def clone(self) -> StateSolver: ...

class MutableStateSolver(StateSolver):
    def setRevision(self, revision: int) -> None: ...

    def getRevision(self) -> int: ...

    def addLink(self, link: "tesseract::scene_graph::Link", joint: "tesseract::scene_graph::Joint") -> bool: ...

    def moveLink(self, joint: "tesseract::scene_graph::Joint") -> bool: ...

    def removeLink(self, name: tesseract_robotics.tesseract_common._tesseract_common.LinkId | str) -> bool: ...

    def replaceJoint(self, joint: "tesseract::scene_graph::Joint") -> bool: ...

    def removeJoint(self, name: tesseract_robotics.tesseract_common._tesseract_common.JointId | str) -> bool: ...

    def moveJoint(self, name: tesseract_robotics.tesseract_common._tesseract_common.JointId | str, parent_link: tesseract_robotics.tesseract_common._tesseract_common.LinkId | str) -> bool: ...

    def changeJointOrigin(self, name: tesseract_robotics.tesseract_common._tesseract_common.JointId | str, new_origin: tesseract_robotics.tesseract_common._tesseract_common.Isometry3d) -> bool: ...

    def changeJointPositionLimits(self, name: tesseract_robotics.tesseract_common._tesseract_common.JointId | str, lower: float, upper: float) -> bool: ...

    def changeJointVelocityLimits(self, name: tesseract_robotics.tesseract_common._tesseract_common.JointId | str, limit: float) -> bool: ...

    def changeJointAccelerationLimits(self, name: tesseract_robotics.tesseract_common._tesseract_common.JointId | str, limit: float) -> bool: ...

    def changeJointJerkLimits(self, name: tesseract_robotics.tesseract_common._tesseract_common.JointId | str, limit: float) -> bool: ...

class KDLStateSolver(StateSolver):
    def __init__(self, scene_graph: "tesseract::scene_graph::SceneGraph") -> None: ...

    def clone(self) -> StateSolver: ...

class OFKTStateSolver(MutableStateSolver):
    def __init__(self, scene_graph: "tesseract::scene_graph::SceneGraph") -> None: ...

    def clone(self) -> StateSolver: ...
