"""tesseract_motion_planners_simple Python bindings"""

import tesseract_robotics.tesseract_command_language._tesseract_command_language
import tesseract_robotics.tesseract_motion_planners._tesseract_motion_planners


class SimpleMotionPlanner:
    def __init__(self, name: str = 'SIMPLE') -> None: ...

    def getName(self) -> str: ...

    def solve(self, request: tesseract_robotics.tesseract_motion_planners._tesseract_motion_planners.PlannerRequest) -> tesseract_robotics.tesseract_motion_planners._tesseract_motion_planners.PlannerResponse: ...

    def terminate(self) -> bool: ...

    def clear(self) -> None: ...

    def clone(self) -> tesseract_robotics.tesseract_motion_planners._tesseract_motion_planners.MotionPlanner: ...

def generateInterpolatedProgram(instructions: tesseract_robotics.tesseract_command_language._tesseract_command_language.CompositeInstruction, env: "tesseract_environment::Environment", state_longest_valid_segment_length: float = 0.08726646259971647, translation_longest_valid_segment_length: float = 0.15, rotation_longest_valid_segment_length: float = 0.08726646259971647, min_steps: int = 1) -> tesseract_robotics.tesseract_command_language._tesseract_command_language.CompositeInstruction:
    """Generate an interpolated program from a composite instruction"""

class SimplePlannerMoveProfile(tesseract_robotics.tesseract_command_language._tesseract_command_language.Profile):
    pass

class SimplePlannerCompositeProfile(tesseract_robotics.tesseract_command_language._tesseract_command_language.Profile):
    def __init__(self) -> None: ...

class SimplePlannerFixedSizeMoveProfile(SimplePlannerMoveProfile):
    def __init__(self, freespace_steps: int = 10, linear_steps: int = 10) -> None: ...

    @property
    def freespace_steps(self) -> int: ...

    @freespace_steps.setter
    def freespace_steps(self, arg: int, /) -> None: ...

    @property
    def linear_steps(self) -> int: ...

    @linear_steps.setter
    def linear_steps(self, arg: int, /) -> None: ...

class SimplePlannerFixedSizeAssignMoveProfile(SimplePlannerMoveProfile):
    def __init__(self, freespace_steps: int = 10, linear_steps: int = 10) -> None: ...

    @property
    def freespace_steps(self) -> int: ...

    @freespace_steps.setter
    def freespace_steps(self, arg: int, /) -> None: ...

    @property
    def linear_steps(self) -> int: ...

    @linear_steps.setter
    def linear_steps(self, arg: int, /) -> None: ...

class SimplePlannerFixedSizeAssignNoIKMoveProfile(SimplePlannerMoveProfile):
    def __init__(self, freespace_steps: int = 10, linear_steps: int = 10) -> None: ...

    @property
    def freespace_steps(self) -> int: ...

    @freespace_steps.setter
    def freespace_steps(self, arg: int, /) -> None: ...

    @property
    def linear_steps(self) -> int: ...

    @linear_steps.setter
    def linear_steps(self, arg: int, /) -> None: ...

class SimplePlannerLVSMoveProfile(SimplePlannerMoveProfile):
    def __init__(self, state_longest_valid_segment_length: float = 0.08726646259971647, translation_longest_valid_segment_length: float = 0.1, rotation_longest_valid_segment_length: float = 0.08726646259971647, min_steps: int = 1, max_steps: int = 2147483647) -> None: ...

    @property
    def state_longest_valid_segment_length(self) -> float: ...

    @state_longest_valid_segment_length.setter
    def state_longest_valid_segment_length(self, arg: float, /) -> None: ...

    @property
    def translation_longest_valid_segment_length(self) -> float: ...

    @translation_longest_valid_segment_length.setter
    def translation_longest_valid_segment_length(self, arg: float, /) -> None: ...

    @property
    def rotation_longest_valid_segment_length(self) -> float: ...

    @rotation_longest_valid_segment_length.setter
    def rotation_longest_valid_segment_length(self, arg: float, /) -> None: ...

    @property
    def min_steps(self) -> int: ...

    @min_steps.setter
    def min_steps(self, arg: int, /) -> None: ...

    @property
    def max_steps(self) -> int: ...

    @max_steps.setter
    def max_steps(self, arg: int, /) -> None: ...

class SimplePlannerLVSNoIKMoveProfile(SimplePlannerMoveProfile):
    def __init__(self, state_longest_valid_segment_length: float = 0.08726646259971647, translation_longest_valid_segment_length: float = 0.1, rotation_longest_valid_segment_length: float = 0.08726646259971647, min_steps: int = 1, max_steps: int = 2147483647) -> None: ...

    @property
    def state_longest_valid_segment_length(self) -> float: ...

    @state_longest_valid_segment_length.setter
    def state_longest_valid_segment_length(self, arg: float, /) -> None: ...

    @property
    def translation_longest_valid_segment_length(self) -> float: ...

    @translation_longest_valid_segment_length.setter
    def translation_longest_valid_segment_length(self, arg: float, /) -> None: ...

    @property
    def rotation_longest_valid_segment_length(self) -> float: ...

    @rotation_longest_valid_segment_length.setter
    def rotation_longest_valid_segment_length(self, arg: float, /) -> None: ...

    @property
    def min_steps(self) -> int: ...

    @min_steps.setter
    def min_steps(self, arg: int, /) -> None: ...

    @property
    def max_steps(self) -> int: ...

    @max_steps.setter
    def max_steps(self, arg: int, /) -> None: ...

class SimplePlannerLVSAssignMoveProfile(SimplePlannerMoveProfile):
    def __init__(self, state_longest_valid_segment_length: float = 0.08726646259971647, translation_longest_valid_segment_length: float = 0.1, rotation_longest_valid_segment_length: float = 0.08726646259971647, min_steps: int = 1, max_steps: int = 2147483647) -> None: ...

    @property
    def state_longest_valid_segment_length(self) -> float: ...

    @state_longest_valid_segment_length.setter
    def state_longest_valid_segment_length(self, arg: float, /) -> None: ...

    @property
    def translation_longest_valid_segment_length(self) -> float: ...

    @translation_longest_valid_segment_length.setter
    def translation_longest_valid_segment_length(self, arg: float, /) -> None: ...

    @property
    def rotation_longest_valid_segment_length(self) -> float: ...

    @rotation_longest_valid_segment_length.setter
    def rotation_longest_valid_segment_length(self, arg: float, /) -> None: ...

    @property
    def min_steps(self) -> int: ...

    @min_steps.setter
    def min_steps(self, arg: int, /) -> None: ...

    @property
    def max_steps(self) -> int: ...

    @max_steps.setter
    def max_steps(self, arg: int, /) -> None: ...

class SimplePlannerLVSAssignNoIKMoveProfile(SimplePlannerMoveProfile):
    def __init__(self, state_longest_valid_segment_length: float = 0.08726646259971647, translation_longest_valid_segment_length: float = 0.1, rotation_longest_valid_segment_length: float = 0.08726646259971647, min_steps: int = 1, max_steps: int = 2147483647) -> None: ...

    @property
    def state_longest_valid_segment_length(self) -> float: ...

    @state_longest_valid_segment_length.setter
    def state_longest_valid_segment_length(self, arg: float, /) -> None: ...

    @property
    def translation_longest_valid_segment_length(self) -> float: ...

    @translation_longest_valid_segment_length.setter
    def translation_longest_valid_segment_length(self, arg: float, /) -> None: ...

    @property
    def rotation_longest_valid_segment_length(self) -> float: ...

    @rotation_longest_valid_segment_length.setter
    def rotation_longest_valid_segment_length(self, arg: float, /) -> None: ...

    @property
    def min_steps(self) -> int: ...

    @min_steps.setter
    def min_steps(self, arg: int, /) -> None: ...

    @property
    def max_steps(self) -> int: ...

    @max_steps.setter
    def max_steps(self, arg: int, /) -> None: ...
